# Generated by Django 5.1.3 on 2025-07-31 21:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FE', '0001_initial'),
        ('INVENTARIO', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='actividades_economicas',
            field=models.ManyToManyField(blank=True, to='FE.actividadeconomica'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='departamento',
            field=models.ForeignKey(blank=True, help_text='Departamento del proveedor', null=True, on_delete=django.db.models.deletion.SET_NULL, to='FE.departamento'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='municipio',
            field=models.ForeignKey(blank=True, help_text='Municipio del proveedor', null=True, on_delete=django.db.models.deletion.SET_NULL, to='FE.municipio'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='tipo_documento',
            field=models.ForeignKey(blank=True, help_text='DUI, NIT, etc.', null=True, on_delete=django.db.models.deletion.CASCADE, to='FE.tiposdocidreceptor'),
        ),
    ]
