# Generated by Django 5.1.3 on 2025-07-03 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FE', '0003_emisor_fe_tipocontribuyente'),
        ('INVENTARIO', '0002_remove_proveedor_actividades_economicas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='actividades_economicas',
            field=models.ManyToManyField(blank=True, to='FE.actividadeconomica'),
        ),
    ]
