# Generated by Django 5.1.3 on 2025-03-11 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('INVENTARIO', '0002_tipoitem_producto_tipo_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='referencia_interna',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
    ]
