# Generated by Django 5.1.3 on 2025-09-02 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('INVENTARIO', '0002_proveedor_actividades_economicas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Pagado', 'Pagado'), ('Devuelto', 'Devuelto'), ('Cancelado', 'Cancelado')], default='Pendiente', max_length=20),
        ),
    ]
