# Generated by Django 5.2.12 on 2026-03-25 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('INVENTARIO', '0002_fix_field_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipoitem',
            name='descripcion',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='tipotributo',
            name='descripcion',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='tipounidadmedida',
            name='descripcion',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='tipovalor',
            name='descripcion',
            field=models.CharField(max_length=500),
        ),
    ]
