# Generated by Django 5.1.3 on 2025-03-12 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('INVENTARIO', '0003_producto_referencia_interna'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoTributo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TipoValor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tributo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=100)),
                ('valor_tributo', models.CharField(max_length=100, null=True)),
                ('tipo_tributo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='INVENTARIO.tipotributo')),
                ('tipo_valor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='INVENTARIO.tipovalor')),
            ],
        ),
        migrations.AddField(
            model_name='producto',
            name='tributo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='INVENTARIO.tributo'),
        ),
    ]
