# Generated by Django 5.1.3 on 2025-03-12 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('INVENTARIO', '0004_tipotributo_tipovalor_tributo_producto_tributo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='tributo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='INVENTARIO.tributo'),
        ),
    ]
