# Generated by Django 5.1.3 on 2025-05-06 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('INVENTARIO', '0008_producto_precio_iva'),
    ]

    operations = [
        migrations.AddField(
            model_name='ajusteinventario',
            name='movimiento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='INVENTARIO.movimientoinventario'),
            preserve_default=False,
        ),
    ]
