# Generated by Django 5.1.3 on 2025-05-19 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('INVENTARIO', '0010_compra_clasificacion_compra_numero_documento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoSujetoExcluido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.CharField(max_length=255)),
                ('preunitario', models.DecimalField(decimal_places=2, max_digits=5)),
                ('precio_compra', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('precio_venta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('referencia_interna', models.CharField(default=None, max_length=50, null=True)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='media/productos/')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('tipo_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='INVENTARIO.tipoitem')),
                ('unidad_medida', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='INVENTARIO.tipounidadmedida')),
            ],
        ),
    ]
