# Generated by Django 5.1.3 on 2025-05-19 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('INVENTARIO', '0011_productosujetoexcluido'),
    ]

    operations = [
        migrations.AddField(
            model_name='productosujetoexcluido',
            name='proveedor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='proveedor', to='INVENTARIO.proveedor'),
            preserve_default=False,
        ),
    ]
