# Generated by Django 5.1.3 on 2025-05-19 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('INVENTARIO', '0012_productosujetoexcluido_proveedor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productosujetoexcluido',
            name='proveedor',
        ),
        migrations.RemoveField(
            model_name='productosujetoexcluido',
            name='tipo_item',
        ),
        migrations.RemoveField(
            model_name='productosujetoexcluido',
            name='unidad_medida',
        ),
        migrations.CreateModel(
            name='ProductoProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.CharField(max_length=255)),
                ('preunitario', models.DecimalField(decimal_places=2, max_digits=5)),
                ('referencia_interna', models.CharField(default=None, max_length=50, null=True)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='media/productos/')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proveedor', to='INVENTARIO.proveedor')),
                ('tipo_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='INVENTARIO.tipoitem')),
                ('unidad_medida', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='INVENTARIO.tipounidadmedida')),
            ],
        ),
    ]
