# Generated by Django 5.1.3 on 2025-05-19 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FE', '0121_alter_detallefacturasujetoexcluido_producto'),
        ('INVENTARIO', '0013_remove_productosujetoexcluido_proveedor_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductoSujetoExcluido',
        ),
    ]
