# Generated by Django 5.1.3 on 2025-05-20 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('INVENTARIO', '0015_proveedor_tipo_documento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proveedor',
            old_name='ruc_nit',
            new_name='num_documento',
        ),
    ]
