# Generated by Django 5.1.3 on 2025-05-20 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FE', '0122_remove_facturasujetoexcluidoelectronica_dteemisor'),
        ('INVENTARIO', '0016_rename_ruc_nit_proveedor_num_documento'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='actividades_economicas',
            field=models.ManyToManyField(blank=True, to='FE.actividadeconomica'),
        ),
    ]
