# Generated by Django 5.1.3 on 2025-05-20 05:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FE', '0122_remove_facturasujetoexcluidoelectronica_dteemisor'),
        ('INVENTARIO', '0017_proveedor_actividades_economicas'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='departamento',
            field=models.ForeignKey(blank=True, help_text='Departamento del proveedor', null=True, on_delete=django.db.models.deletion.SET_NULL, to='FE.departamento'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='municipio',
            field=models.ForeignKey(blank=True, help_text='Municipio del proveedor', null=True, on_delete=django.db.models.deletion.SET_NULL, to='FE.municipio'),
        ),
    ]
