# Generated by Django 5.1.3 on 2025-12-10 22:58

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre de la Categoría')),
            ],
            options={
                'verbose_name': 'Categoría del Menú',
                'verbose_name_plural': 'Categorías del Menú',
            },
        ),
        migrations.CreateModel(
            name='Mesero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='codigo de identificaciòn')),
                ('activo', models.BooleanField(default=True, verbose_name='Mesero Activo')),
            ],
            options={
                'verbose_name': 'Mesero',
                'verbose_name_plural': 'Meseros',
            },
        ),
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=10, unique=True, verbose_name='Número de Mesa')),
                ('capacidad', models.PositiveSmallIntegerField(default=4, verbose_name='Capacidad de personas')),
                ('area', models.CharField(default='Salón Principal', max_length=50, verbose_name='Área o Zona')),
                ('es_vip', models.BooleanField(default=False, verbose_name='Mesa VIP (Prioridad)')),
                ('estado', models.CharField(choices=[('LIBRE', 'Libre'), ('OCUPADA', 'Ocupada'), ('PENDIENTE_PAGO', 'Pendiente de Pago')], default='LIBRE', max_length=20, verbose_name='Estado Actual')),
                ('mesero_asignado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mesas_asignadas', to='RESTAURANTE.mesero', verbose_name='Mesero Asignado')),
            ],
            options={
                'verbose_name': 'Mesa',
                'verbose_name_plural': 'Mesas',
            },
        ),
        migrations.CreateModel(
            name='Platillo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del Platillo')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción o Ingredientes')),
                ('precio_venta', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Precio de Venta')),
                ('disponible', models.BooleanField(default=True, verbose_name='Disponible para Venta')),
                ('es_preparado', models.BooleanField(default=True, verbose_name='Requiere Cocina/Preparación')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='platillos', to='RESTAURANTE.categoriamenu')),
            ],
            options={
                'verbose_name': 'Platillo / Ítem del Menú',
                'verbose_name_plural': 'Platillos / Ítems del Menú',
            },
        ),
    ]
