# Generated by Django 5.1.3 on 2025-12-11 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RESTAURANTE', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriamenu',
            name='color',
            field=models.CharField(default='#007bff', max_length=7, verbose_name='Color (Hexadecimal)'),
        ),
    ]
