# Generated by Django 5.1.3 on 2025-12-12 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RESTAURANTE', '0003_platillo_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platillo',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='Menu/'),
        ),
    ]
