# Generated by Django 5.1.3 on 2025-12-12 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RESTAURANTE', '0004_alter_platillo_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsignacionMesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('es_fija', models.BooleanField(default=False)),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('activa', models.BooleanField(default=True)),
                ('mesa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='RESTAURANTE.mesa')),
                ('mesero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='RESTAURANTE.mesero')),
            ],
            options={
                'verbose_name': 'Asignacion de mesa',
                'verbose_name_plural': 'Asignaciones de mesas',
            },
        ),
    ]
