# Generated by Django 5.1.3 on 2025-12-12 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RESTAURANTE', '0005_asignacionmesa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mesa',
            name='mesero_asignado',
        ),
        migrations.AlterField(
            model_name='mesa',
            name='area',
            field=models.CharField(max_length=50, verbose_name='Área o Zona'),
        ),
    ]
