# Generated by Django 5.1.3 on 2025-12-12 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RESTAURANTE', '0006_remove_mesa_mesero_asignado_alter_mesa_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='mesero',
            name='nombre',
            field=models.CharField(default=1, max_length=120, verbose_name='Nombre mesero'),
            preserve_default=False,
        ),
    ]
