# Generated by Django 5.1.3 on 2025-12-12 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RESTAURANTE', '0007_mesero_nombre'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='asignacionmesa',
            constraint=models.UniqueConstraint(condition=models.Q(('activa', True)), fields=('mesa',), name='uniq_mesa_asignacion_activa'),
        ),
    ]
