# Generated by Django 5.1.3 on 2026-01-02 22:48

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AUTENTICACION', '0003_alter_user_role'),
        ('INVENTARIO', '0001_initial'),
        ('RESTAURANTE', '0010_remove_asignacionmesa_uniq_mesa_asignacion_activa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='platillo',
            name='codigo',
            field=models.CharField(default=1, max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='platillo',
            name='producto',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='platillo', to='INVENTARIO.producto'),
        ),
        migrations.AlterField(
            model_name='mesero',
            name='codigo',
            field=models.CharField(max_length=20, unique=True, verbose_name='codigo de identificaciòn'),
        ),
        migrations.CreateModel(
            name='Caja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_apertura', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de apertura')),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de cierre')),
                ('monto_inicial', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('monto_cierre', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('total_ventas', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('total_efectivo', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('total_tarjeta', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('monto_final', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('diferencia', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('total_propinas', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('estado', models.CharField(choices=[('ABIERTA', 'Abierta'), ('CERRADA', 'Cerrada')], default='ABIERTA', max_length=20)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AUTENTICACION.perfilusuario')),
            ],
        ),
        migrations.CreateModel(
            name='MovimientosCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_movimiento', models.CharField(choices=[('INGRESO', 'Ingreso'), ('RETIRO', 'Retiro')], max_length=20)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('motivo', models.CharField(max_length=200)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('caja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='RESTAURANTE.caja')),
            ],
        ),
    ]
