# Generated by Django 5.1.3 on 2026-01-05 04:30

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FE', '0004_emisor_fe_es_restaurante'),
        ('RESTAURANTE', '0011_platillo_codigo_platillo_producto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mesa',
            name='estado',
            field=models.CharField(choices=[('LIBRE', 'Libre'), ('OCUPADA', 'Ocupada'), ('PENDIENTE_ORDEN', 'Pendiente de Orden'), ('PENDIENTE_PAGO', 'Pendiente de Pago')], default='LIBRE', max_length=20, verbose_name='Estado Actual'),
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('ABIERTO', 'Abierto'), ('CERRADO', 'Cerrado'), ('PAGADO', 'Pagado'), ('ANULADO', 'Anulado')], default='ABIERTO', max_length=20)),
                ('creado_el', models.DateTimeField(default=django.utils.timezone.now)),
                ('cerrado_el', models.DateTimeField(blank=True, null=True)),
                ('pagado_el', models.DateTimeField(blank=True, null=True)),
                ('notas', models.CharField(blank=True, default='', max_length=300)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('descuento_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('iva_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('propina', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('caja', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='RESTAURANTE.caja')),
                ('factura', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedido_origen', to='FE.facturaelectronica')),
                ('mesa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='RESTAURANTE.mesa')),
                ('mesero', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='RESTAURANTE.mesero')),
                ('receptor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='FE.receptor_fe')),
            ],
            options={
                'ordering': ['-creado_el'],
            },
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('precio_unitario', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('descuento_pct', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('aplica_iva', models.BooleanField(default=True)),
                ('subtotal_linea', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('descuento_monto', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('iva_monto', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_linea', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('notas', models.CharField(blank=True, default='', max_length=250)),
                ('creado_el', models.DateTimeField(default=django.utils.timezone.now)),
                ('platillo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_pedido', to='RESTAURANTE.platillo')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='RESTAURANTE.pedido')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['mesa', 'estado'], name='RESTAURANTE_mesa_id_e60c18_idx'),
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['creado_el'], name='RESTAURANTE_creado__153908_idx'),
        ),
    ]
