# Generated by Django 5.1.3 on 2026-01-07 22:21

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RESTAURANTE', '0012_alter_mesa_estado_pedido_detallepedido_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='mesa',
            name='estado',
            field=models.CharField(choices=[('LIBRE', 'Libre'), ('OCUPADA', 'Ocupada'), ('ENTREGADO', 'Entregado'), ('PENDIENTE_ORDEN', 'Pendiente de Orden'), ('PENDIENTE_PAGO', 'Pendiente de Pago')], default='LIBRE', max_length=20, verbose_name='Estado Actual'),
        ),
        migrations.CreateModel(
            name='Cocinero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, verbose_name='Nombre cocinero')),
                ('pin', models.CharField(max_length=20, unique=True, verbose_name='codigo de identificaciòn')),
                ('activo', models.BooleanField(default=True, verbose_name='Mesero Activo')),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cocinero',
                'verbose_name_plural': 'Cocineros',
            },
        ),
        migrations.CreateModel(
            name='Comanda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(default=1)),
                ('estado', models.CharField(choices=[('ENVIADA', 'Enviada'), ('EN_PREPARACION', 'En preparación'), ('CERRADA', 'Cerrada'), ('ANULADA', 'Anulada')], default='ENVIADA', max_length=20)),
                ('creada_el', models.DateTimeField(default=django.utils.timezone.now)),
                ('iniciada_el', models.DateTimeField(blank=True, null=True)),
                ('cerrada_el', models.DateTimeField(blank=True, null=True)),
                ('notas', models.CharField(blank=True, default='', max_length=250)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comandas', to='RESTAURANTE.pedido')),
            ],
            options={
                'ordering': ['-creada_el'],
            },
        ),
        migrations.CreateModel(
            name='ComandaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=160)),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('notas', models.CharField(blank=True, default='', max_length=250)),
                ('enviado_el', models.DateTimeField(default=django.utils.timezone.now)),
                ('iniciado_el', models.DateTimeField(blank=True, null=True)),
                ('listo_el', models.DateTimeField(blank=True, null=True)),
                ('entregado_el', models.DateTimeField(blank=True, null=True)),
                ('comanda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='RESTAURANTE.comanda')),
                ('detalle_pedido', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comanda_items', to='RESTAURANTE.detallepedido')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddConstraint(
            model_name='comanda',
            constraint=models.UniqueConstraint(fields=('pedido', 'numero'), name='uniq_comanda_por_pedido_numero'),
        ),
    ]
