# Generated by Django 5.1.3 on 2026-01-12 06:02

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RESTAURANTE', '0013_alter_mesa_estado_cocinero_comanda_comandaitem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mesa',
            name='estado',
            field=models.CharField(choices=[('LIBRE', 'Libre'), ('OCUPADA', 'Ocupada'), ('ENTREGADO', 'Entregado'), ('PENDIENTE_ORDEN', 'Pendiente de Orden'), ('PENDIENTE_PAGO', 'Pendiente de Pago'), ('PAGADO', 'Pagado')], default='LIBRE', max_length=20, verbose_name='Estado Actual'),
        ),
        migrations.CreateModel(
            name='CuentaPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Cuenta', max_length=60)),
                ('estado', models.CharField(choices=[('ABIERTA', 'Abierta'), ('CERRADA', 'Cerrada'), ('PAGADA', 'Pagada'), ('ANULADA', 'Anulada')], default='ABIERTA', max_length=20)),
                ('creado_el', models.DateTimeField(default=django.utils.timezone.now)),
                ('cerrado_el', models.DateTimeField(blank=True, null=True)),
                ('pagado_el', models.DateTimeField(blank=True, null=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('descuento_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('iva_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('propina', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuentas', to='RESTAURANTE.pedido')),
            ],
        ),
        migrations.AddField(
            model_name='detallepedido',
            name='cuenta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='detalles', to='RESTAURANTE.cuentapedido'),
        ),
        migrations.AddIndex(
            model_name='detallepedido',
            index=models.Index(fields=['pedido', 'cuenta'], name='RESTAURANTE_pedido__5c678a_idx'),
        ),
        migrations.AddIndex(
            model_name='cuentapedido',
            index=models.Index(fields=['pedido', 'estado'], name='RESTAURANTE_pedido__fe195e_idx'),
        ),
    ]
