# Generated by Django 5.1.3 on 2026-01-13 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RESTAURANTE', '0014_alter_mesa_estado_cuentapedido_detallepedido_cuenta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='division_confirmada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='detallepedido',
            constraint=models.CheckConstraint(condition=models.Q(('cantidad__gt', 0)), name='detallepedido_cantidad_gt_0'),
        ),
    ]
