# Generated by Django 5.1.3 on 2026-01-16 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RESTAURANTE', '0015_pedido_division_confirmada_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='detallepedido',
            name='detallepedido_cantidad_gt_0',
        ),
        migrations.AddConstraint(
            model_name='detallepedido',
            constraint=models.CheckConstraint(condition=models.Q(('cantidad__gte', 0)), name='detallepedido_cantidad_gte_0'),
        ),
    ]
