# Generated by Django 5.1.3 on 2026-01-16 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RESTAURANTE', '0016_remove_detallepedido_detallepedido_cantidad_gt_0_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaCocina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_cocina', models.CharField(max_length=50, unique=True, verbose_name='Nombre del area de cocina')),
            ],
            options={
                'verbose_name': 'Area de codina',
                'verbose_name_plural': 'Areas de cocina',
            },
        ),
        migrations.AlterModelOptions(
            name='area',
            options={'verbose_name': 'Area restaurante', 'verbose_name_plural': 'Areas restaurante'},
        ),
        migrations.AlterField(
            model_name='area',
            name='nombre',
            field=models.CharField(max_length=50, unique=True, verbose_name='Nombre del area'),
        ),
        migrations.AlterField(
            model_name='cocinero',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Cocinero activo'),
        ),
        migrations.AlterField(
            model_name='mesa',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='area', to='RESTAURANTE.area'),
        ),
        migrations.AddField(
            model_name='cocinero',
            name='area_cocina',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='RESTAURANTE.areacocina'),
        ),
        migrations.AddField(
            model_name='platillo',
            name='area_cocina',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='RESTAURANTE.areacocina', verbose_name='area cocina'),
        ),
    ]
