# Generated by Django 5.1.3 on 2026-01-19 00:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RESTAURANTE', '0017_areacocina_alter_area_options_alter_area_nombre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comanda',
            name='area_cocina',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.PROTECT, related_name='comandas', to='RESTAURANTE.areacocina'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='comanda',
            constraint=models.UniqueConstraint(condition=models.Q(('estado__in', ['ENVIADA', 'EN_PREPARACION'])), fields=('pedido', 'area_cocina', 'estado'), name='uniq_comanda_activa_por_area'),
        ),
    ]
