# Generated by Django 5.1.3 on 2026-01-19 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AUTENTICACION', '0004_alter_user_role'),
        ('RESTAURANTE', '0018_comanda_area_cocina_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BilletesYMonedas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='caja',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movimientoscaja',
            name='autorizado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='AUTENTICACION.perfilusuario'),
        ),
        migrations.AddField(
            model_name='movimientoscaja',
            name='categoria',
            field=models.CharField(choices=[('PROVEEDOR', 'Pago a Proveedor'), ('COMPRA_LOCAL', 'Compra Insumos'), ('NOMINA', 'Adelanto Sueldo'), ('OTROS', 'Otros')], default='OTROS', max_length=50),
        ),
    ]
