# Generated by Django 5.1.3 on 2026-01-19 22:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RESTAURANTE', '0019_billetesymonedas_caja_observaciones_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CajaDetalleArqueo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('APERTURA', 'Apertura'), ('CIERRE', 'Cierre')], max_length=10)),
                ('cantidad', models.PositiveIntegerField(default=0)),
                ('caja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_arqueo', to='RESTAURANTE.caja')),
                ('denominacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='RESTAURANTE.billetesymonedas')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('caja', 'denominacion', 'tipo'), name='uniq_caja_denominacion_tipo')],
            },
        ),
    ]
