# Generated by Django 5.1.3 on 2026-01-21 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FE', '0005_alter_facturaelectronica_numero_control'),
        ('RESTAURANTE', '0020_cajadetallearqueo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='factura',
        ),
        migrations.AddField(
            model_name='cuentapedido',
            name='factura',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cuenta_pedido', to='FE.facturaelectronica'),
        ),
    ]
