# Generated by Django 5.1.3 on 2026-01-23 21:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RESTAURANTE', '0021_remove_pedido_factura_cuentapedido_factura'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cajero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, verbose_name='Nombre Cajero')),
                ('pin', models.CharField(max_length=20, unique=True, verbose_name='codigo de identificaciòn')),
                ('activo', models.BooleanField(default=True, verbose_name='Cajero activo')),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cajero',
                'verbose_name_plural': 'Cajeros',
            },
        ),
    ]
