# Generated by Django 5.1.3 on 2026-02-04 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RESTAURANTE', '0022_cajero'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='comanda',
            name='uniq_comanda_activa_por_area',
        ),
    ]
