# Generated by Django 5.1.3 on 2026-02-06 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RESTAURANTE', '0023_remove_comanda_uniq_comanda_activa_por_area'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cuentapedido',
            options={'verbose_name': 'Cuenta', 'verbose_name_plural': 'Cuentas'},
        ),
        migrations.AlterModelOptions(
            name='platillo',
            options={'verbose_name': 'Platillo', 'verbose_name_plural': 'Platillos'},
        ),
    ]
