version: "3.9"

services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/app
      - ./backend/db.sqlite3:/app/db.sqlite3
    ports:
      - "8787:8000"
    environment:
      - DEBUG=1

  frontend:
    build: ./intracoe-frontend
    volumes:
      - ./intracoe-frontend:/app
    ports:
      - "5173:5173"
    command: ["npm", "run", "dev"]
