# Generated by Django 5.1.3 on 2025-09-04 17:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AUTENTICACION', '0001_initial'),
        ('FE', '0124_alter_token_data_token_alter_token_data_token_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='emisor_activo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios_activos', to='FE.emisor_fe'),
        ),
        migrations.CreateModel(
            name='UsuarioEmisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('es_predeterminado', models.BooleanField(default=False)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('emisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios_rel', to='FE.emisor_fe')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emisores_rel', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vínculo Usuario–Emisor',
                'verbose_name_plural': 'Vínculos Usuario–Emisor',
                'unique_together': {('user', 'emisor')},
            },
        ),
    ]
