# Generated by Django 5.1.3 on 2025-04-26 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AUTENTICACION', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionServidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True, null=True)),
                ('url_endpoint', models.URLField(blank=True, null=True)),
                ('ruta_archivo', models.CharField(blank=True, max_length=100, null=True)),
                ('contraseña', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
