# Generated by Django 5.1.3 on 2025-04-26 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AUTENTICACION', '0002_configuracionservidor'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionservidor',
            name='codigo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
