# Generated by Django 5.1.3 on 2025-04-30 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AUTENTICACION', '0002_configuracionservidor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='configuracionservidor',
            old_name='codigo',
            new_name='clave',
        ),
        migrations.AddField(
            model_name='configuracionservidor',
            name='fecha_creacion',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
