# Generated by Django 5.1.3 on 2025-12-22 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AUTENTICACION', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrador'), ('vendedor', 'Vendedor'), ('supervisor', 'Supervisor'), ('cliente', 'Cliente'), ('mesero', 'Mesero')], default='cliente', max_length=20),
        ),
    ]
