# Generated by Django 5.1.3 on 2025-10-08 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AUTENTICACION', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('scope', models.CharField(choices=[('general', 'General'), ('fe', 'Facturación Electrónica')], db_index=True, default='general', max_length=20)),
                ('host', models.CharField(max_length=200)),
                ('port', models.PositiveIntegerField(default=465)),
                ('use_ssl', models.BooleanField(default=True)),
                ('use_tls', models.BooleanField(default=False)),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=255)),
                ('from_email', models.EmailField(help_text='Remitente por defecto (FROM)', max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Perfil de correo',
                'verbose_name_plural': 'Perfiles de correo',
            },
        ),
    ]
