# Generated by Django 5.1.3 on 2025-04-30 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AUTENTICACION', '0003_rename_codigo_configuracionservidor_clave_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuracionservidor',
            name='ruta_archivo',
        ),
        migrations.AddField(
            model_name='configuracionservidor',
            name='descripcion',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='configuracionservidor',
            name='valor',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
