# Generated by Django 5.1.3 on 2025-04-30 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AUTENTICACION', '0004_remove_configuracionservidor_ruta_archivo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracionservidor',
            name='url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='configuracionservidor',
            name='url_endpoint',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
