# Generated by Django 5.1.3 on 2026-01-22 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AUTENTICACION', '0004_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrador'), ('vendedor', 'Vendedor'), ('supervisor', 'Supervisor'), ('cliente', 'Cliente'), ('mesero', 'Mesero'), ('cocinero', 'Cocinero'), ('cajero', 'Cajero')], default='cliente', max_length=20),
        ),
    ]
