# Generated by Django 5.2.12 on 2026-03-24 21:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AUTENTICACION', '0005_alter_user_role'),
        ('FE', '0008_alter_consolidacionfactura_factura_destino_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('tiene_facturacion', models.BooleanField(default=True, verbose_name='Facturación Electrónica')),
                ('tiene_ventas', models.BooleanField(default=True, verbose_name='Ventas')),
                ('tiene_compras', models.BooleanField(default=False, verbose_name='Compras')),
                ('tiene_inventario', models.BooleanField(default=False, verbose_name='Inventario')),
                ('tiene_contabilidad', models.BooleanField(default=False, verbose_name='Contabilidad')),
                ('tiene_rrhh', models.BooleanField(default=False, verbose_name='RRHH / Nómina')),
                ('tiene_restaurante', models.BooleanField(default=False, verbose_name='Restaurante / POS')),
            ],
            options={
                'verbose_name': 'Plan',
                'verbose_name_plural': 'Planes',
            },
        ),
        migrations.CreateModel(
            name='Suscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, help_text='Dejar vacío = sin vencimiento', null=True)),
                ('activo', models.BooleanField(default=True)),
                ('emisor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='suscripcion', to='FE.emisor_fe')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='suscripciones', to='AUTENTICACION.plan')),
            ],
            options={
                'verbose_name': 'Suscripción',
                'verbose_name_plural': 'Suscripciones',
            },
        ),
    ]
