# Generated by Django 5.2.12 on 2026-03-26 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AUTENTICACION', '0007_limpiar_duplicados_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracionservidor',
            name='clave',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
