# Generated by Django 5.2.12 on 2026-03-30 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AUTENTICACION', '0008_config_clave_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionalidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(help_text='Ej: ventas.clientes, facturacion.contingencias', max_length=80, unique=True)),
                ('nombre', models.CharField(help_text='Nombre visible', max_length=120)),
                ('modulo', models.CharField(choices=[('ventas', 'Ventas'), ('compras', 'Compras'), ('facturacion', 'Facturación'), ('inventario', 'Inventario'), ('contabilidad', 'Contabilidad'), ('rrhh', 'RRHH / Nómina'), ('restaurante', 'Restaurante / POS')], max_length=30)),
                ('icono', models.CharField(blank=True, default='bi-circle', help_text='Clase Bootstrap Icons', max_length=50)),
            ],
            options={
                'verbose_name': 'Funcionalidad',
                'verbose_name_plural': 'Funcionalidades',
                'ordering': ['modulo', 'nombre'],
            },
        ),
        migrations.AddField(
            model_name='plan',
            name='funcionalidades',
            field=models.ManyToManyField(blank=True, related_name='planes', to='AUTENTICACION.funcionalidad', verbose_name='Funcionalidades incluidas'),
        ),
    ]
