# Generated by Django 5.2.12 on 2026-03-30 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AUTENTICACION', '0010_cargar_funcionalidades_iniciales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionalidad',
            name='modulo',
            field=models.CharField(choices=[('sistema', 'Sistema'), ('ventas', 'Ventas'), ('compras', 'Compras'), ('facturacion', 'Facturación'), ('inventario', 'Inventario'), ('contabilidad', 'Contabilidad'), ('rrhh', 'RRHH / Nómina'), ('restaurante', 'Restaurante / POS')], max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrador'), ('suscriptor', 'Suscriptor'), ('vendedor', 'Vendedor'), ('supervisor', 'Supervisor'), ('cliente', 'Cliente'), ('mesero', 'Mesero'), ('cocinero', 'Cocinero'), ('cajero', 'Cajero')], default='suscriptor', max_length=20),
        ),
    ]
