# Generated by Django 5.1.3 on 2025-03-04 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dte', '0005_alter_numerocontrol_anio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='numerocontrol',
            name='anio',
            field=models.IntegerField(unique=True),
        ),
    ]
