# Generated by Django 5.1.3 on 2025-03-04 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dte', '0004_numerocontrol_tipo_dte_alter_numerocontrol_anio_and_more'),
        ('dte', '0007_alter_numerocontrol_anio_and_more'),
    ]

    operations = [
    ]
