# Generated by Django 5.1.3 on 2025-03-04 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dte', '0008_merge_20250304_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='numerocontrol',
            name='tipo_dte',
            field=models.CharField(default='00', max_length=2),
        ),
    ]
