# Generated by Django 5.1.3 on 2025-03-04 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dte', '0009_alter_numerocontrol_tipo_dte'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='numerocontrol',
            unique_together=set(),
        ),
    ]
