# Generated by Django 5.1.3 on 2025-03-04 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dte', '0010_alter_numerocontrol_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='numerocontrol',
            unique_together={('anio', 'tipo_dte')},
        ),
    ]
