# Generated by Django 5.2.12 on 2026-03-26 04:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CONTABILIDAD', '0002_cuentaporcobrar_cuentaporpagar_pagocobro_pagopagar'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionContable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dias_vencimiento_cxc', models.PositiveIntegerField(default=30, verbose_name='Días vencimiento CxC')),
                ('dias_vencimiento_cxp', models.PositiveIntegerField(default=30, verbose_name='Días vencimiento CxP')),
                ('auto_confirmar_asientos', models.BooleanField(default=True, verbose_name='Confirmar asientos automáticamente')),
                ('cuenta_banco', models.ForeignKey(blank=True, help_text='Ej: 1102 - Bancos', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='CONTABILIDAD.cuentacontable', verbose_name='Banco')),
                ('cuenta_caja', models.ForeignKey(blank=True, help_text='Ej: 1101 - Caja General', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='CONTABILIDAD.cuentacontable', verbose_name='Caja / Efectivo')),
                ('cuenta_compras', models.ForeignKey(blank=True, help_text='Ej: 5101 - Compras o Costo de Ventas', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='CONTABILIDAD.cuentacontable', verbose_name='Compras / Costo')),
                ('cuenta_cxc', models.ForeignKey(blank=True, help_text='Ej: 1103 - Cuentas por Cobrar Comerciales', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='CONTABILIDAD.cuentacontable', verbose_name='Cuentas por cobrar')),
                ('cuenta_cxp', models.ForeignKey(blank=True, help_text='Ej: 2101 - Cuentas por Pagar Comerciales', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='CONTABILIDAD.cuentacontable', verbose_name='Cuentas por pagar')),
                ('cuenta_ingresos_ventas', models.ForeignKey(blank=True, help_text='Ej: 4101 - Ventas', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='CONTABILIDAD.cuentacontable', verbose_name='Ingresos por ventas')),
                ('cuenta_inventario', models.ForeignKey(blank=True, help_text='Ej: 1104 - Inventario de Mercaderías', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='CONTABILIDAD.cuentacontable', verbose_name='Inventario')),
                ('cuenta_iva_credito_fiscal', models.ForeignKey(blank=True, help_text='Ej: 1105 - IVA Crédito Fiscal (IVA pagado en compras)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='CONTABILIDAD.cuentacontable', verbose_name='IVA Crédito Fiscal')),
                ('cuenta_iva_debito_fiscal', models.ForeignKey(blank=True, help_text='Ej: 2104 - IVA Débito Fiscal (IVA cobrado en ventas)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='CONTABILIDAD.cuentacontable', verbose_name='IVA Débito Fiscal')),
            ],
            options={
                'verbose_name': 'Configuración Contable',
                'verbose_name_plural': 'Configuración Contable',
            },
        ),
    ]
