# Generated by Django 5.1.3 on 2025-07-03 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FE', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emisor_fe',
            name='tipoContribuyente',
        ),
    ]
