# Generated by Django 5.1.3 on 2025-03-04 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FE', '0034_numerocontrol_tipo_dte_alter_numerocontrol_anio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='numerocontrol',
            name='tipo_dte',
            field=models.CharField(default='00', max_length=2),
        ),
    ]
