# Generated by Django 5.1.3 on 2025-03-07 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FE', '0039_facturaelectronica_recibido_mh'),
    ]

    operations = [
        migrations.AddField(
            model_name='emisor_fe',
            name='nombre_establecimiento',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre Establecimiento'),
        ),
        migrations.CreateModel(
            name='EventoInvalidacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_dte', models.CharField(max_length=2)),
                ('codigo_generacion', models.CharField(blank=True, max_length=50)),
                ('sello_recibido', models.CharField(blank=True, max_length=255, null=True)),
                ('numero_control', models.CharField(blank=True, max_length=31)),
                ('fecha_emision', models.DateField(auto_now_add=True)),
                ('monto_iva', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('codigo_generacion_r', models.CharField(blank=True, max_length=50)),
                ('motivo_anulacion', models.CharField(blank=True, max_length=255, null=True)),
                ('nombre_solicita', models.CharField(max_length=255, verbose_name='Nombre o Razón Social')),
                ('tipo_documento_solicita', models.IntegerField(null=True)),
                ('numero_documento_solicita', models.CharField(blank=True, max_length=20, null=True)),
                ('factura', models.ForeignKey(help_text='Evento de invalidacion a la que pertenece la Factura', on_delete=django.db.models.deletion.CASCADE, related_name='dte_invalidacion', to='FE.facturaelectronica')),
                ('tipo_anulacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dte_tipo_invalidacion_FE', to='FE.tipoinvalidacion')),
            ],
        ),
    ]
