# Generated by Django 5.1.3 on 2025-03-07 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FE', '0040_emisor_fe_nombre_establecimiento_eventoinvalidacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventoinvalidacion',
            name='codigo_generacion',
        ),
        migrations.RemoveField(
            model_name='eventoinvalidacion',
            name='fecha_emision',
        ),
        migrations.RemoveField(
            model_name='eventoinvalidacion',
            name='monto_iva',
        ),
        migrations.RemoveField(
            model_name='eventoinvalidacion',
            name='numero_control',
        ),
        migrations.RemoveField(
            model_name='eventoinvalidacion',
            name='sello_recibido',
        ),
        migrations.RemoveField(
            model_name='eventoinvalidacion',
            name='tipo_dte',
        ),
    ]
