# Generated by Django 5.1.3 on 2025-03-07 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FE', '0041_remove_eventoinvalidacion_codigo_generacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emisor_fe',
            name='tipo_documento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='FE.tiposdocidreceptor'),
        ),
    ]
