# Generated by Django 5.1.3 on 2025-03-07 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FE', '0047_alter_eventoinvalidacion_json_invalidacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventoinvalidacion',
            name='json_firmado',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
