# Generated by Django 5.1.3 on 2025-03-08 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FE', '0049_eventoinvalidacion_firmado'),
        ('INVENTARIO', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Producto',
            new_name='Producto_fe',
        ),
        migrations.AlterField(
            model_name='detallefactura',
            name='producto',
            field=models.ForeignKey(help_text='Producto asociado a este detalle', on_delete=django.db.models.deletion.CASCADE, to='INVENTARIO.producto'),
        ),
    ]
