# Generated by Django 5.1.3 on 2025-03-08 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FE', '0050_rename_producto_producto_fe_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Producto_fe',
        ),
    ]
