# Generated by Django 5.1.3 on 2025-03-08 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FE', '0051_delete_producto_fe'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventoinvalidacion',
            name='recibido_mh',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='eventoinvalidacion',
            name='sello_recepcion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
