# Generated by Django 5.1.3 on 2025-03-10 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FE', '0053_alter_eventoinvalidacion_tipo_documento_solicita'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventoinvalidacion',
            name='estado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='facturaelectronica',
            name='estado',
            field=models.BooleanField(default=False),
        ),
    ]
