# Generated by Django 5.1.3 on 2025-03-11 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FE', '0054_eventoinvalidacion_estado_facturaelectronica_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipoitem',
            name='descripcion',
            field=models.CharField(max_length=100),
        ),
    ]
