# Generated by Django 5.1.3 on 2025-03-11 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FE', '0055_alter_tipoitem_descripcion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TipoItem',
        ),
    ]
