# Generated by Django 5.1.3 on 2025-03-12 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FE', '0060_rename_porcentaje_tributo_tributo_valor_tributo'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoValor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='tributo',
            name='tipo_valor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='FE.tipovalor'),
        ),
    ]
