# Generated by Django 5.1.3 on 2025-03-12 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FE', '0061_tipovalor_tributo_tipo_valor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tributo',
            name='valor_tributo',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
