# Generated by Django 5.1.3 on 2025-03-13 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FE', '0064_rename_tipo_anulacion_eventoinvalidacion_tipo_invalidacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturaelectronica',
            name='documento_relacionado',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='facturaelectronica',
            name='tipo_documento_relacionar',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
