# Generated by Django 5.1.3 on 2025-03-25 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FE', '0067_eventocontingencia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emisor_fe',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='media/productos/'),
        ),
    ]
