# Generated by Django 5.1.3 on 2025-03-27 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FE', '0068_emisor_fe_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receptor_fe',
            name='nombreComercial',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
