# Generated by Django 5.1.3 on 2025-04-02 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FE', '0070_alter_detallefactura_precio_unitario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallefactura',
            name='no_gravado',
            field=models.DecimalField(decimal_places=6, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='detallefactura',
            name='pre_sug_venta',
            field=models.DecimalField(decimal_places=6, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='detallefactura',
            name='ventas_exentas',
            field=models.DecimalField(decimal_places=6, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='detallefactura',
            name='ventas_gravadas',
            field=models.DecimalField(decimal_places=6, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='detallefactura',
            name='ventas_no_sujetas',
            field=models.DecimalField(decimal_places=6, max_digits=10, null=True),
        ),
    ]
