# Generated by Django 5.1.3 on 2025-04-05 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FE', '0072_alter_detallefactura_iva_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventocontingencia',
            name='estado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='facturaelectronica',
            name='contingencia',
            field=models.BooleanField(default=False),
        ),
    ]
