# Generated by Django 5.1.3 on 2025-04-07 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FE', '0074_eventocontingencia_factura_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventocontingencia',
            name='motivo_contingencia',
        ),
        migrations.AddField(
            model_name='emisor_fe',
            name='clave_privada',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='emisor_fe',
            name='clave_publica',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='eventocontingencia',
            name='fecha_modificacion',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='eventocontingencia',
            name='firmado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='eventocontingencia',
            name='hora_modificacion',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='eventocontingencia',
            name='json_firmado',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventocontingencia',
            name='json_original',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
