# Generated by Django 5.1.3 on 2025-04-08 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FE', '0076_tipocontingencia_motivo_contingencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventocontingencia',
            name='recibido_mh',
            field=models.BooleanField(default=False),
        ),
    ]
