# Generated by Django 5.1.3 on 2025-04-09 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FE', '0081_facturaelectronica_contingencia_recibida_mh'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventocontingencia',
            name='factura',
        ),
        migrations.AddField(
            model_name='eventocontingencia',
            name='finalizado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='facturaelectronica',
            name='dtecontingencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contingencia_dte', to='FE.eventocontingencia'),
        ),
    ]
