# Generated by Django 5.1.3 on 2025-04-09 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FE', '0084_alter_eventocontingencia_finalizado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventocontingencia',
            name='finalizado',
            field=models.BooleanField(default=False),
        ),
    ]
