# Generated by Django 5.1.3 on 2025-04-09 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FE', '0085_alter_eventocontingencia_finalizado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventocontingencia',
            name='factura',
            field=models.ManyToManyField(blank=True, related_name='detalles_dte', to='FE.facturaelectronica'),
        ),
    ]
