# Generated by Django 5.1.3 on 2025-04-10 01:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FE', '0087_lotecontingencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lotecontingencia',
            name='eventocontingencia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='FE.eventocontingencia'),
        ),
    ]
