# Generated by Django 5.1.3 on 2025-04-10 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FE', '0088_alter_lotecontingencia_eventocontingencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='lotecontingencia',
            name='fecha_modificacion',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='lotecontingencia',
            name='fecha_transmicion',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='lotecontingencia',
            name='hora_modificacion',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='lotecontingencia',
            name='hora_transmision',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
    ]
