# Generated by Django 5.1.3 on 2025-04-10 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FE', '0091_lotecontingencia_factura_lotes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lotecontingencia',
            name='factura_lotes',
        ),
    ]
