# Generated by Django 5.1.3 on 2025-04-11 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FE', '0094_rename_fecha_transmicion_eventocontingencia_fecha_transmision_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lotecontingencia',
            name='eventocontingencia',
        ),
        migrations.AddField(
            model_name='lotecontingencia',
            name='factura',
            field=models.ManyToManyField(blank=True, related_name='facturas_lote', to='FE.facturaelectronica'),
        ),
    ]
