# Generated by Django 5.1.3 on 2025-04-12 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FE', '0095_remove_lotecontingencia_eventocontingencia_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventocontingencia',
            name='factura',
        ),
        migrations.AddField(
            model_name='facturaelectronica',
            name='fecha_modificacion',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='facturaelectronica',
            name='hora_modificacion',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
    ]
