# Generated by Django 5.1.3 on 2025-04-12 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FE', '0097_remove_lotecontingencia_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventocontingencia',
            name='lotecontingencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lotes_evento', to='FE.lotecontingencia'),
        ),
        migrations.RemoveField(
            model_name='lotecontingencia',
            name='factura',
        ),
        migrations.AddField(
            model_name='lotecontingencia',
            name='factura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='facturas_lote', to='FE.facturaelectronica'),
        ),
    ]
