# Generated by Django 5.1.3 on 2025-04-14 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FE', '0100_lotecontingencia_finalizado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventocontingencia',
            name='lotecontingencia',
        ),
    ]
