# Generated by Django 5.1.3 on 2025-04-14 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FE', '0102_eventocontingencia_lotecontingencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lotecontingencia',
            name='factura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lotecontingencia', to='FE.facturaelectronica'),
        ),
    ]
