# Generated by Django 5.1.3 on 2025-04-15 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FE', '0104_remove_eventocontingencia_lotecontingencia_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventocontingencia',
            old_name='estado',
            new_name='rechazado',
        ),
        migrations.AddField(
            model_name='eventocontingencia',
            name='observaciones',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='lotecontingencia',
            name='factura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lotes_factura', to='FE.facturaelectronica'),
        ),
    ]
