# Generated by Django 5.1.3 on 2025-04-15 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FE', '0105_rename_estado_eventocontingencia_rechazado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventocontingencia',
            name='motivo_contingencia',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
