# Generated by Django 5.1.3 on 2025-04-15 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FE', '0106_eventocontingencia_motivo_contingencia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventocontingencia',
            name='motivo_contingencia',
        ),
    ]
