# Generated by Django 5.1.3 on 2025-04-16 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FE', '0107_remove_eventocontingencia_motivo_contingencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventocontingencia',
            name='hora_sello_recibido',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
    ]
