# Generated by Django 5.1.3 on 2025-04-25 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FE', '0114_emisor_fe_representante'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturaelectronica',
            name='envio_coreo',
            field=models.BooleanField(default=True),
        ),
    ]
