# Generated by Django 5.1.3 on 2025-05-16 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FE', '0117_rename_envio_coreo_facturaelectronica_envio_correo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emisor_fe',
            name='tipoContribuyente',
            field=models.CharField(choices=[('Gran Contribuyente', 'Gran Contribuyente'), ('Mediano Contribuyente', 'Mediano Contribuyente'), ('Pequeño Contribuyente', 'Pequeño Contribuyente'), ('Emprendedor', 'Emprendedor')], default='Pequeño Contribuyente', max_length=40),
        ),
    ]
