# Generated by Django 5.1.3 on 2025-05-19 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FE', '0119_facturasujetoexcluidoelectronica_and_more'),
        ('INVENTARIO', '0011_productosujetoexcluido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallefacturasujetoexcluido',
            name='descripcion',
        ),
        migrations.AddField(
            model_name='detallefacturasujetoexcluido',
            name='producto',
            field=models.ForeignKey(default=1, help_text='Producto de sujeto exclusivo asociado a este detalle', on_delete=django.db.models.deletion.CASCADE, to='INVENTARIO.productosujetoexcluido'),
            preserve_default=False,
        ),
    ]
