# Generated by Django 5.1.3 on 2025-05-20 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FE', '0121_alter_detallefacturasujetoexcluido_producto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facturasujetoexcluidoelectronica',
            name='dteemisor',
        ),
    ]
