# Generated by Django 5.1.3 on 2025-05-20 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FE', '0122_remove_facturasujetoexcluidoelectronica_dteemisor'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturasujetoexcluidoelectronica',
            name='dteemisor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='facturas_emisor_sujeto_excluido_FE', to='FE.emisor_fe'),
            preserve_default=False,
        ),
    ]
