# Generated by Django 5.1.3 on 2025-05-20 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FE', '0123_facturasujetoexcluidoelectronica_dteemisor'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventoinvalidacion',
            name='facturaSujetoExcluido',
            field=models.ForeignKey(blank=True, help_text='Evento de invalidacion solo para sujeto exclusivo', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dte_invalidacion_sujeto_excluido', to='FE.facturasujetoexcluidoelectronica'),
        ),
        migrations.AlterField(
            model_name='eventoinvalidacion',
            name='factura',
            field=models.ForeignKey(blank=True, help_text='Evento de invalidacion a la que pertenece la Factura', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dte_invalidacion', to='FE.facturaelectronica'),
        ),
    ]
