# Generated by Django 5.1.3 on 2025-09-23 16:10

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActividadEconomica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, verbose_name='Código de Actividad Económica')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'actividad económica',
                'verbose_name_plural': 'actividades económicas',
            },
        ),
        migrations.CreateModel(
            name='Ambiente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CondicionOperacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Descuento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcentaje', models.DecimalField(decimal_places=2, max_digits=5)),
                ('descripcion', models.CharField(max_length=50)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('estdo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='DetalleFacturaSujetoExcluido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1, help_text='Cantidad del producto')),
                ('tipo_item', models.CharField(blank=True, max_length=150, null=True)),
                ('precio_unitario', models.DecimalField(decimal_places=6, help_text='Precio unitario del producto', max_digits=10)),
                ('tiene_descuento', models.BooleanField(default=False)),
                ('descuento', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Porcentaje de descuento aplicado a esta línea', max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Emisor_fe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nit', models.CharField(max_length=20, verbose_name='NIT del Emisor')),
                ('nrc', models.CharField(max_length=50, null=True)),
                ('nombre_razon_social', models.CharField(max_length=255, verbose_name='Nombre o Razón Social')),
                ('nombre_comercial', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre Comercial')),
                ('direccion_comercial', models.TextField(verbose_name='Dirección Comercial')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Electrónico')),
                ('codigo_establecimiento', models.CharField(blank=True, max_length=10, null=True, verbose_name='Código de Establecimiento')),
                ('codigo_punto_venta', models.CharField(blank=True, max_length=50, null=True, verbose_name='Codigo de Punto de Venta')),
                ('nombre_establecimiento', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre Establecimiento')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='media/productos/')),
                ('clave_privada', models.CharField(blank=True, max_length=255, null=True)),
                ('clave_publica', models.CharField(blank=True, max_length=255, null=True)),
                ('tipoContribuyente', models.CharField(choices=[('Gran Contribuyente', 'Gran Contribuyente'), ('Mediano Contribuyente', 'Mediano Contribuyente'), ('Pequeño Contribuyente', 'Pequeño Contribuyente'), ('Emprendedor', 'Emprendedor')], default='Pequeño Contribuyente', max_length=40)),
                ('imprime_termica', models.BooleanField(default=False, verbose_name='Imprimir en térmica (80mm)')),
            ],
        ),
        migrations.CreateModel(
            name='EventoContingencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_generacion', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('sello_recepcion', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_transmision', models.DateField(auto_now_add=True, null=True)),
                ('hora_transmision', models.TimeField(auto_now_add=True, null=True)),
                ('fecha_modificacion', models.DateField(auto_now_add=True, null=True)),
                ('hora_modificacion', models.TimeField(auto_now_add=True, null=True)),
                ('firmado', models.BooleanField(default=False)),
                ('json_original', models.JSONField(blank=True, null=True)),
                ('json_firmado', models.JSONField(blank=True, null=True)),
                ('recibido_mh', models.BooleanField(default=False)),
                ('f_fin', models.DateField(auto_now_add=True, null=True)),
                ('h_fin', models.TimeField(auto_now_add=True, null=True)),
                ('finalizado', models.BooleanField(default=False)),
                ('rechazado', models.BooleanField(default=False)),
                ('observaciones', models.CharField(blank=True, max_length=3000, null=True)),
                ('fecha_sello_recibido', models.DateTimeField(blank=True, null=True)),
                ('cantidad_lote', models.IntegerField(null=True)),
                ('motivo_contingencia', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EventoInvalidacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_generacion', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('fecha_anulacion', models.DateField(auto_now_add=True, null=True)),
                ('hora_anulacion', models.TimeField(auto_now_add=True, null=True)),
                ('codigo_generacion_r', models.CharField(blank=True, max_length=50, null=True)),
                ('motivo_anulacion', models.CharField(blank=True, max_length=255, null=True)),
                ('nombre_solicita', models.CharField(max_length=255, null=True, verbose_name='Nombre o Razón Social')),
                ('tipo_documento_solicita', models.CharField(blank=True, max_length=20, null=True)),
                ('numero_documento_solicita', models.CharField(blank=True, max_length=20, null=True)),
                ('solicita_invalidacion', models.CharField(blank=True, max_length=15, null=True)),
                ('json_invalidacion', models.JSONField(blank=True, null=True)),
                ('json_firmado', models.JSONField(blank=True, null=True)),
                ('firmado', models.BooleanField(default=False)),
                ('sello_recepcion', models.CharField(blank=True, max_length=255, null=True)),
                ('recibido_mh', models.BooleanField(default=False)),
                ('estado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='FacturaElectronica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=50)),
                ('numero_control', models.CharField(blank=True, max_length=31, unique=True)),
                ('codigo_generacion', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('motivocontin', models.CharField(blank=True, max_length=350, null=True)),
                ('fecha_emision', models.DateField(auto_now_add=True)),
                ('hora_emision', models.TimeField(auto_now_add=True)),
                ('total_no_sujetas', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('total_exentas', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('total_gravadas', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('sub_total_ventas', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('descuen_no_sujeto', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('descuento_exento', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('descuento_gravado', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('por_descuento', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('total_descuento', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('sub_total', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('iva_retenido', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('retencion_renta', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('total_operaciones', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('total_no_gravado', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('total_pagar', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('total_letras', models.CharField(max_length=250, null=True)),
                ('total_iva', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('iva_percibido', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('saldo_favor', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('formas_Pago', models.JSONField(blank=True, null=True)),
                ('firmado', models.BooleanField(default=False)),
                ('json_original', models.JSONField()),
                ('json_firmado', models.JSONField(blank=True, null=True)),
                ('sello_recepcion', models.CharField(blank=True, max_length=255, null=True)),
                ('recibido_mh', models.BooleanField(default=False)),
                ('estado', models.BooleanField(default=False)),
                ('contingencia', models.BooleanField(default=False)),
                ('contingencia_recibida_mh', models.BooleanField(default=False)),
                ('base_imponible', models.BooleanField(default=False)),
                ('fecha_modificacion', models.DateField(auto_now_add=True, null=True)),
                ('hora_modificacion', models.TimeField(auto_now_add=True, null=True)),
                ('envio_correo', models.BooleanField(default=False)),
                ('envio_correo_contingencia', models.BooleanField(default=False)),
                ('seguro_exportacion', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('flete_exportacion', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='FacturaSujetoExcluidoElectronica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=50)),
                ('numero_control', models.CharField(blank=True, max_length=31, unique=True)),
                ('codigo_generacion', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('motivocontin', models.CharField(blank=True, max_length=350, null=True)),
                ('fecha_emision', models.DateField(auto_now_add=True)),
                ('hora_emision', models.TimeField(auto_now_add=True)),
                ('descuento', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('total_descuento', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('sub_total', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('iva_retenido', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('retencion_renta', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('total_operaciones', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('total_pagar', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('total_letras', models.CharField(max_length=250, null=True)),
                ('formas_Pago', models.JSONField(blank=True, null=True)),
                ('firmado', models.BooleanField(default=False)),
                ('json_original', models.JSONField()),
                ('json_firmado', models.JSONField(blank=True, null=True)),
                ('sello_recepcion', models.CharField(blank=True, max_length=255, null=True)),
                ('recibido_mh', models.BooleanField(default=False)),
                ('estado', models.BooleanField(default=False)),
                ('contingencia', models.BooleanField(default=False)),
                ('contingencia_recibida_mh', models.BooleanField(default=False)),
                ('fecha_modificacion', models.DateField(auto_now_add=True, null=True)),
                ('hora_modificacion', models.TimeField(auto_now_add=True, null=True)),
                ('envio_correo', models.BooleanField(default=False)),
                ('envio_correo_contingencia', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='FormasPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='INCOTERMS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='LoteContingencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recibido_mh', models.BooleanField(default=False)),
                ('finalizado', models.BooleanField(default=False)),
                ('fecha_transmicion', models.DateField(auto_now_add=True, null=True)),
                ('hora_transmision', models.TimeField(auto_now_add=True, null=True)),
                ('fecha_modificacion', models.DateField(auto_now_add=True, null=True)),
                ('hora_modificacion', models.TimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Modelofacturacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='NumeroControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_establecimiento', models.CharField(blank=True, default='0000', max_length=4, null=True)),
                ('codigo_punto_venta', models.CharField(blank=True, default='0001', max_length=4, null=True)),
                ('anio', models.IntegerField()),
                ('secuencia', models.IntegerField(default=1)),
                ('tipo_dte', models.CharField(default='00', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='OtrosDicumentosAsociado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Plazo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Receptor_fe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_documento', models.CharField(blank=True, max_length=20, null=True)),
                ('nrc', models.CharField(blank=True, max_length=8, null=True)),
                ('nombre', models.CharField(max_length=250)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('telefono', models.CharField(blank=True, max_length=30, null=True)),
                ('correo', models.EmailField(blank=True, max_length=254, null=True)),
                ('nombreComercial', models.CharField(blank=True, max_length=150, null=True)),
                ('lat', models.DecimalField(blank=True, decimal_places=6, help_text='Latitud (WGS84)', max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(Decimal('-90')), django.core.validators.MaxValueValidator(Decimal('90'))])),
                ('lng', models.DecimalField(blank=True, decimal_places=6, help_text='Longitud (WGS84)', max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(Decimal('-180')), django.core.validators.MaxValueValidator(Decimal('180'))])),
                ('geocoded_at', models.DateTimeField(blank=True, null=True)),
                ('geocode_source', models.CharField(blank=True, default='', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='RecintoFiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RegimenExportacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='representanteEmisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('numero_documento', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_dte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=50)),
                ('version', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoContingencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=150)),
                ('motivo_contingencia', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoDocContingencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TipoDomicilioFiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TipoDonacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TipoGeneracionDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TipoInvalidacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TipoMoneda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TipoPersona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TipoRetencionIVAMH',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TiposDocIDReceptor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='TiposEstablecimientos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TiposServicio_Medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TipoTransmision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TipoTransporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Token_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nit_empresa', models.CharField(max_length=20, unique=True)),
                ('password_hacienda', models.CharField(max_length=255)),
                ('password_privado', models.CharField(default='1', max_length=255)),
                ('token', models.CharField(blank=True, max_length=500, null=True)),
                ('token_type', models.CharField(default='Bearer', max_length=255)),
                ('roles', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activado', models.BooleanField(default=False, null=True)),
                ('fecha_caducidad', models.DateTimeField(default=django.utils.timezone.now, null=True)),
            ],
            options={
                'verbose_name': 'Token Data',
                'verbose_name_plural': 'Token Data',
            },
        ),
        migrations.CreateModel(
            name='DetalleFactura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1, help_text='Cantidad del producto')),
                ('iva_item', models.DecimalField(decimal_places=6, default=Decimal('0.00'), max_digits=10, null=True)),
                ('precio_unitario', models.DecimalField(decimal_places=6, help_text='Precio unitario del producto', max_digits=10)),
                ('ventas_no_sujetas', models.DecimalField(decimal_places=6, max_digits=10, null=True)),
                ('ventas_exentas', models.DecimalField(decimal_places=6, max_digits=10, null=True)),
                ('ventas_gravadas', models.DecimalField(decimal_places=6, max_digits=10, null=True)),
                ('pre_sug_venta', models.DecimalField(decimal_places=6, max_digits=10, null=True)),
                ('no_gravado', models.DecimalField(decimal_places=6, max_digits=10, null=True)),
                ('tiene_descuento', models.BooleanField(default=False)),
                ('saldo_favor', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('tipo_documento_relacionar', models.CharField(blank=True, max_length=50, null=True)),
                ('documento_relacionado', models.CharField(blank=True, max_length=100, null=True)),
                ('descuento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='FE.descuento')),
            ],
        ),
    ]
