# Generated by Django 5.1.3 on 2025-09-23 16:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('FE', '0001_initial'),
        ('INVENTARIO', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='detallefactura',
            name='producto',
            field=models.ForeignKey(help_text='Producto asociado a este detalle', on_delete=django.db.models.deletion.CASCADE, to='INVENTARIO.producto'),
        ),
        migrations.AddField(
            model_name='detallefactura',
            name='unidad_medida',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='INVENTARIO.tipounidadmedida'),
        ),
        migrations.AddField(
            model_name='detallefacturasujetoexcluido',
            name='codigo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='INVENTARIO.tipoitem'),
        ),
        migrations.AddField(
            model_name='detallefacturasujetoexcluido',
            name='producto',
            field=models.ForeignKey(help_text='Producto de sujeto exclusivo asociado a este detalle', on_delete=django.db.models.deletion.CASCADE, to='INVENTARIO.productoproveedor'),
        ),
        migrations.AddField(
            model_name='detallefacturasujetoexcluido',
            name='unidad_medida',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='INVENTARIO.tipounidadmedida'),
        ),
        migrations.AddField(
            model_name='emisor_fe',
            name='actividades_economicas',
            field=models.ManyToManyField(to='FE.actividadeconomica', verbose_name='Actividades Económicas'),
        ),
        migrations.AddField(
            model_name='emisor_fe',
            name='ambiente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FE.ambiente'),
        ),
        migrations.AddField(
            model_name='facturaelectronica',
            name='condicion_operacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='FE.condicionoperacion'),
        ),
        migrations.AddField(
            model_name='facturaelectronica',
            name='dteemisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facturas_emisor_FE', to='FE.emisor_fe'),
        ),
        migrations.AddField(
            model_name='facturaelectronica',
            name='tipoItemEmisor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='INVENTARIO.tipoitem'),
        ),
        migrations.AddField(
            model_name='facturaelectronica',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eventoinvalidacion',
            name='factura',
            field=models.ForeignKey(blank=True, help_text='Evento de invalidacion a la que pertenece la Factura', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dte_invalidacion', to='FE.facturaelectronica'),
        ),
        migrations.AddField(
            model_name='detallefactura',
            name='factura',
            field=models.ForeignKey(help_text='Factura a la que pertenece este detalle', on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='FE.facturaelectronica'),
        ),
        migrations.AddField(
            model_name='facturasujetoexcluidoelectronica',
            name='condicion_operacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='FE.condicionoperacion'),
        ),
        migrations.AddField(
            model_name='facturasujetoexcluidoelectronica',
            name='dteemisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facturas_emisor_sujeto_excluido_FE', to='FE.emisor_fe'),
        ),
        migrations.AddField(
            model_name='facturasujetoexcluidoelectronica',
            name='dtesujetoexcluido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facturas_sujeto_excluido_FE', to='INVENTARIO.proveedor'),
        ),
        migrations.AddField(
            model_name='eventoinvalidacion',
            name='facturaSujetoExcluido',
            field=models.ForeignKey(blank=True, help_text='Evento de invalidacion solo para sujeto exclusivo', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dte_invalidacion_sujeto_excluido', to='FE.facturasujetoexcluidoelectronica'),
        ),
        migrations.AddField(
            model_name='detallefacturasujetoexcluido',
            name='factura',
            field=models.ForeignKey(help_text='Factura a la que pertenece este detalle', on_delete=django.db.models.deletion.CASCADE, related_name='detallesSujetoExcluido', to='FE.facturasujetoexcluidoelectronica'),
        ),
        migrations.AddField(
            model_name='facturaelectronica',
            name='incoterms',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='FE.incoterms'),
        ),
        migrations.AddField(
            model_name='lotecontingencia',
            name='evento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lotes_contingencia', to='FE.eventocontingencia'),
        ),
        migrations.AddField(
            model_name='lotecontingencia',
            name='factura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lotes_de_factura', to='FE.facturaelectronica'),
        ),
        migrations.AddField(
            model_name='facturasujetoexcluidoelectronica',
            name='tipomodelo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='FE.modelofacturacion'),
        ),
        migrations.AddField(
            model_name='facturaelectronica',
            name='tipomodelo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='FE.modelofacturacion'),
        ),
        migrations.AddField(
            model_name='municipio',
            name='departamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FE.departamento'),
        ),
        migrations.AddField(
            model_name='emisor_fe',
            name='municipio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='FE.municipio'),
        ),
        migrations.AlterUniqueTogether(
            name='numerocontrol',
            unique_together={('anio', 'tipo_dte')},
        ),
        migrations.AddField(
            model_name='departamento',
            name='pais',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='FE.pais'),
        ),
        migrations.AddField(
            model_name='receptor_fe',
            name='actividades_economicas',
            field=models.ManyToManyField(to='FE.actividadeconomica', verbose_name='Actividades Económicas'),
        ),
        migrations.AddField(
            model_name='receptor_fe',
            name='municipio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='FE.municipio'),
        ),
        migrations.AddField(
            model_name='receptor_fe',
            name='pais',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='FE.pais'),
        ),
        migrations.AddField(
            model_name='facturaelectronica',
            name='dtereceptor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facturas_receptor_FE', to='FE.receptor_fe'),
        ),
        migrations.AddField(
            model_name='facturaelectronica',
            name='recintoFiscal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='FE.recintofiscal'),
        ),
        migrations.AddField(
            model_name='facturaelectronica',
            name='regimenExportacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='FE.regimenexportacion'),
        ),
        migrations.AddField(
            model_name='emisor_fe',
            name='representante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='FE.representanteemisor'),
        ),
        migrations.AddField(
            model_name='facturasujetoexcluidoelectronica',
            name='tipo_dte',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='FE.tipo_dte'),
        ),
        migrations.AddField(
            model_name='facturaelectronica',
            name='tipo_dte',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='FE.tipo_dte'),
        ),
        migrations.AddField(
            model_name='facturasujetoexcluidoelectronica',
            name='tipocontingencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='FE.tipocontingencia'),
        ),
        migrations.AddField(
            model_name='facturaelectronica',
            name='tipocontingencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='FE.tipocontingencia'),
        ),
        migrations.AddField(
            model_name='eventocontingencia',
            name='tipo_contingencia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='FE.tipocontingencia'),
        ),
        migrations.AddField(
            model_name='eventoinvalidacion',
            name='tipo_invalidacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dte_tipo_invalidacion_FE', to='FE.tipoinvalidacion'),
        ),
        migrations.AddField(
            model_name='facturasujetoexcluidoelectronica',
            name='tipomoneda',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='FE.tipomoneda'),
        ),
        migrations.AddField(
            model_name='facturaelectronica',
            name='tipomoneda',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='FE.tipomoneda'),
        ),
        migrations.AddField(
            model_name='receptor_fe',
            name='tipo_persona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='FE.tipopersona', verbose_name='Tipo de Persona'),
        ),
        migrations.AddField(
            model_name='representanteemisor',
            name='tipo_documento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='FE.tiposdocidreceptor'),
        ),
        migrations.AddField(
            model_name='receptor_fe',
            name='tipo_documento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='FE.tiposdocidreceptor'),
        ),
        migrations.AddField(
            model_name='emisor_fe',
            name='tipo_documento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='FE.tiposdocidreceptor'),
        ),
        migrations.AddField(
            model_name='emisor_fe',
            name='tipoestablecimiento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='FE.tiposestablecimientos'),
        ),
        migrations.AddField(
            model_name='facturasujetoexcluidoelectronica',
            name='tipotransmision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='FE.tipotransmision'),
        ),
        migrations.AddField(
            model_name='facturaelectronica',
            name='tipotransmision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='FE.tipotransmision'),
        ),
    ]
