# Generated by Django 5.1.3 on 2025-07-03 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FE', '0002_remove_emisor_fe_tipocontribuyente'),
    ]

    operations = [
        migrations.AddField(
            model_name='emisor_fe',
            name='tipoContribuyente',
            field=models.CharField(choices=[('Gran Contribuyente', 'Gran Contribuyente'), ('Mediano Contribuyente', 'Mediano Contribuyente'), ('Pequeño Contribuyente', 'Pequeño Contribuyente'), ('Emprendedor', 'Emprendedor')], default='Pequeño Contribuyente', max_length=40),
        ),
    ]
