# Generated by Django 5.1.3 on 2025-12-10 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FE', '0003_receptor_fe_created_at_receptor_fe_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='emisor_fe',
            name='es_restaurante',
            field=models.BooleanField(default=False, verbose_name='Es restaurante'),
        ),
    ]
