# Generated by Django 5.1.3 on 2026-01-10 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FE', '0004_emisor_fe_es_restaurante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturaelectronica',
            name='numero_control',
            field=models.CharField(blank=True, max_length=31),
        ),
    ]
