# Generated by Django 5.1.3 on 2026-02-06 20:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FE', '0005_alter_facturaelectronica_numero_control'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigTipDte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcentaje', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('emisor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='config_tip', to='FE.emisor_fe')),
            ],
            options={
                'verbose_name': 'Tip',
                'verbose_name_plural': 'Tips',
            },
        ),
    ]
