# Generated by Django 5.1.3 on 2026-02-10 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FE', '0006_configtipdte'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsolidacionFactura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_consolidacion', models.DateTimeField(auto_now_add=True)),
                ('factura_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facturas_hijas_consolidadas', to='FE.facturaelectronica')),
                ('factura_origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consolidaciones_como_origen', to='FE.facturaelectronica')),
            ],
            options={
                'verbose_name': 'Consolidación de Factura',
                'unique_together': {('factura_origen',)},
            },
        ),
    ]
