# Generated by Django 5.1.3 on 2026-02-10 22:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FE', '0007_consolidacionfactura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consolidacionfactura',
            name='factura_destino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facturas_consolidadas', to='FE.facturaelectronica'),
        ),
        migrations.AlterField(
            model_name='consolidacionfactura',
            name='factura_origen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consolidacion_origen', to='FE.facturaelectronica'),
        ),
    ]
