# Generated by Django 5.2.12 on 2026-03-24 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FE', '0008_alter_consolidacionfactura_factura_destino_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emisor_fe',
            name='color_sidebar',
            field=models.CharField(default='#ffffff', max_length=7, verbose_name='Color barra lateral (hex)'),
        ),
        migrations.AddField(
            model_name='emisor_fe',
            name='color_topbar',
            field=models.CharField(default='#0d47a1', max_length=7, verbose_name='Color barra superior (hex)'),
        ),
    ]
