# Generated by Django 5.2.12 on 2026-03-25 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FE', '0009_emisor_colores'),
    ]

    operations = [
        migrations.AddField(
            model_name='emisor_fe',
            name='modo_demo',
            field=models.BooleanField(default=False, help_text='No envía a Hacienda, protege datos demo y muestra indicador visual.', verbose_name='Modo demostración'),
        ),
    ]
