# Generated by Django 5.2.12 on 2026-03-27 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FE', '0011_ampliar_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallefactura',
            name='descripcion_adicional',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Descripción adicional (aduana)'),
        ),
        migrations.AddField(
            model_name='emisor_fe',
            name='porcentaje_percepcion_iva',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=5, verbose_name='% Percepción IVA'),
        ),
        migrations.AddField(
            model_name='emisor_fe',
            name='porcentaje_retencion_iva',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=5, verbose_name='% Retención IVA'),
        ),
        migrations.AddField(
            model_name='emisor_fe',
            name='porcentaje_retencion_renta',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=5, verbose_name='% Retención Renta'),
        ),
        migrations.AddField(
            model_name='receptor_fe',
            name='aplica_percepcion',
            field=models.BooleanField(default=False, verbose_name='Aplica percepción IVA'),
        ),
        migrations.AddField(
            model_name='receptor_fe',
            name='aplica_retencion',
            field=models.BooleanField(default=False, verbose_name='Aplica retención'),
        ),
    ]
