# Generated by Django 5.2.12 on 2026-03-27 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FE', '0012_add_retention_perception_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receptor_fe',
            name='aplica_retencion',
        ),
        migrations.AddField(
            model_name='receptor_fe',
            name='aplica_retencion_iva',
            field=models.BooleanField(default=False, verbose_name='Aplica retención IVA'),
        ),
        migrations.AddField(
            model_name='receptor_fe',
            name='aplica_retencion_renta',
            field=models.BooleanField(default=False, verbose_name='Aplica retención renta'),
        ),
    ]
