# Generated by Django 5.2.12 on 2026-03-29 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FE', '0013_split_retencion_flags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emisor_fe',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/'),
        ),
    ]
