# Generated by Django 5.1.3 on 2025-03-04 19:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FE', '0033_rename_ambiene_emisor_fe_ambiente'),
    ]

    operations = [
        migrations.AddField(
            model_name='numerocontrol',
            name='tipo_dte',
            field=models.CharField(default=uuid.uuid4, max_length=2),
        ),
        migrations.AlterField(
            model_name='numerocontrol',
            name='anio',
            field=models.IntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='numerocontrol',
            unique_together={('anio', 'tipo_dte')},
        ),
    ]
