# Generated by Django 5.1.3 on 2025-03-04 17:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FE', '0034_numerocontrol_tipo_dte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='numerocontrol',
            name='anio',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='numerocontrol',
            name='tipo_dte',
            field=models.CharField(default=uuid.uuid4, max_length=2),
        ),
    ]
