# Generated by Django 5.1.3 on 2025-03-05 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FE', '0035_alter_numerocontrol_tipo_dte'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturaelectronica',
            name='iva_percibido',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='receptor_fe',
            name='nombreComercial',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
