# Generated by Django 5.1.3 on 2025-03-04 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FE', '0036_alter_numerocontrol_anio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='numerocontrol',
            name='anio',
            field=models.IntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='numerocontrol',
            unique_together={('anio', 'tipo_dte')},
        ),
    ]
