# Generated by Django 5.1.3 on 2025-03-07 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FE', '0043_eventoinvalidacion_codigo_generacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventoinvalidacion',
            name='json_original',
            field=models.JSONField(default=None),
        ),
    ]
