# Generated by Django 5.1.3 on 2025-03-07 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FE', '0044_eventoinvalidacion_json_original'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventoinvalidacion',
            name='json_original',
            field=models.JSONField(),
        ),
    ]
