# Generated by Django 5.1.3 on 2025-03-07 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FE', '0045_alter_eventoinvalidacion_json_original'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventoinvalidacion',
            old_name='json_original',
            new_name='json_invalidacion',
        ),
    ]
