# Generated by Django 5.1.3 on 2025-03-13 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FE', '0056_delete_tipoitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturaelectronica',
            name='motivocontin',
            field=models.CharField(blank=True, max_length=350, null=True),
        ),
        migrations.AlterField(
            model_name='facturaelectronica',
            name='tipocontingencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='FE.tipocontingencia'),
        ),
    ]
