# Generated by Django 5.1.3 on 2025-03-12 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FE', '0056_delete_tipoitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallefactura',
            name='base_imponible',
            field=models.BooleanField(default=False),
        ),
    ]
