# Generated by Django 5.1.3 on 2025-03-12 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FE', '0058_tipotributo_tributo'),
    ]

    operations = [
        migrations.AddField(
            model_name='tributo',
            name='porcentaje_tributo',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
