# Generated by Django 5.1.3 on 2025-03-12 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FE', '0062_alter_tributo_valor_tributo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tributo',
            name='tipo_tributo',
        ),
        migrations.RemoveField(
            model_name='tributo',
            name='tipo_valor',
        ),
        migrations.DeleteModel(
            name='TipoTributo',
        ),
        migrations.DeleteModel(
            name='TipoValor',
        ),
        migrations.DeleteModel(
            name='Tributo',
        ),
    ]
