# Generated by Django 5.1.3 on 2025-03-13 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FE', '0065_facturaelectronica_documento_relacionado_and_more'),
        ('INVENTARIO', '0006_tipounidadmedida_alter_producto_unidad_medida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallefactura',
            name='unidad_medida',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='INVENTARIO.tipounidadmedida'),
        ),
        migrations.DeleteModel(
            name='TipoUnidadMedida',
        ),
    ]
