# Generated by Django 5.1.3 on 2025-03-22 14:13

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FE', '0065_facturaelectronica_documento_relacionado_and_more'),
        ('INVENTARIO', '0007_remove_producto_descuento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallefactura',
            name='unidad_medida',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='INVENTARIO.tipounidadmedida'),
        ),
        migrations.RenameField(
            model_name='detallefactura',
            old_name='base_imponible',
            new_name='tiene_descuento',
        ),
        migrations.AddField(
            model_name='detallefactura',
            name='saldo_favor',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='facturaelectronica',
            name='base_imponible',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='facturaelectronica',
            name='formas_Pago',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='facturaelectronica',
            name='saldo_favor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='detallefactura',
            name='descuento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='FE.descuento'),
        ),
        migrations.AlterField(
            model_name='facturaelectronica',
            name='documento_relacionado',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='facturaelectronica',
            name='motivocontin',
            field=models.CharField(blank=True, max_length=350, null=True),
        ),
        migrations.AlterField(
            model_name='facturaelectronica',
            name='tipo_documento_relacionar',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='facturaelectronica',
            name='tipocontingencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='FE.tipocontingencia'),
        ),
        migrations.DeleteModel(
            name='TipoUnidadMedida',
        ),
    ]
