# Generated by Django 5.1.3 on 2025-03-14 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FE', '0065_facturaelectronica_documento_relacionado_and_more'),
        ('INVENTARIO', '0007_remove_producto_descuento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallefactura',
            name='unidad_medida',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='INVENTARIO.tipounidadmedida'),
        ),
        migrations.AddField(
            model_name='detallefactura',
            name='tiene_descuento',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='facturaelectronica',
            name='motivocontin',
            field=models.CharField(blank=True, max_length=350, null=True),
        ),
        migrations.AlterField(
            model_name='facturaelectronica',
            name='tipocontingencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='FE.tipocontingencia'),
        ),
        migrations.DeleteModel(
            name='TipoUnidadMedida',
        ),
    ]
