# Generated by Django 5.1.3 on 2025-03-13 20:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FE', '0066_alter_detallefactura_unidad_medida_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallefactura',
            name='descuento',
        ),
        migrations.AddField(
            model_name='detallefactura',
            name='por_descuento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='FE.descuento'),
        ),
        migrations.AddField(
            model_name='detallefactura',
            name='tiene_descuento',
            field=models.BooleanField(default=False),
        ),
    ]
