# Generated by Django 5.1.3 on 2025-03-24 20:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FE', '0066_alter_detallefactura_unidad_medida_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoContingencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_generacion', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('fecha_transmicion', models.DateField(auto_now_add=True, null=True)),
                ('hora_transmision', models.TimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='facturaelectronica',
            name='documento_relacionado',
        ),
        migrations.RemoveField(
            model_name='facturaelectronica',
            name='tipo_documento_relacionar',
        ),
        migrations.AddField(
            model_name='detallefactura',
            name='documento_relacionado',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='detallefactura',
            name='tipo_documento_relacionar',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
