# Generated by Django 5.1.3 on 2025-03-17 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FE', '0067_alter_detallefactura_descuento'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturaelectronica',
            name='formas_Pago',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='facturaelectronica',
            name='saldo_favor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='facturaelectronica',
            name='documento_relacionado',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='facturaelectronica',
            name='tipo_documento_relacionar',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
