# Generated by Django 5.1.3 on 2025-03-14 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FE', '0057_alter_facturaelectronica_motivocontin_and_more'),
        ('FE', '0068_rename_por_descuento_detallefactura_descuento'),
    ]

    operations = [
    ]
