# Generated by Django 5.1.3 on 2025-03-20 14:28

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FE', '0068_facturaelectronica_formas_pago_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallefactura',
            name='base_imponible',
        ),
        migrations.AddField(
            model_name='detallefactura',
            name='saldo_favor',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='facturaelectronica',
            name='base_imponible',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='facturaelectronica',
            name='documento_relacionado',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='facturaelectronica',
            name='formas_Pago',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
