# Generated by Django 5.1.3 on 2025-03-14 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FE', '0069_merge_20250314_0814'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturaelectronica',
            name='saldo_favor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
