# Generated by Django 5.1.3 on 2025-04-01 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FE', '0069_alter_receptor_fe_nombrecomercial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallefactura',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=6, help_text='Precio unitario del producto', max_digits=10),
        ),
    ]
