# Generated by Django 5.1.3 on 2025-03-14 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FE', '0070_facturaelectronica_saldo_favor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturaelectronica',
            name='documento_relacionado',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='facturaelectronica',
            name='tipo_documento_relacionar',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
