# Generated by Django 5.1.3 on 2025-04-02 14:08

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FE', '0071_alter_detallefactura_no_gravado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallefactura',
            name='iva_item',
            field=models.DecimalField(decimal_places=6, default=Decimal('0.00'), max_digits=10, null=True),
        ),
    ]
