# Generated by Django 5.1.3 on 2025-03-15 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FE', '0071_alter_facturaelectronica_documento_relacionado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturaelectronica',
            name='formas_Pago',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
