# Generated by Django 5.1.3 on 2025-03-18 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FE', '0072_facturaelectronica_formas_pago'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallefactura',
            name='base_imponible',
        ),
    ]
