# Generated by Django 5.1.3 on 2025-03-18 17:11

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FE', '0073_remove_detallefactura_base_imponible'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallefactura',
            name='saldo_favor',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='eventoinvalidacion',
            name='base_imponible',
            field=models.BooleanField(default=False),
        ),
    ]
