# Generated by Django 5.1.3 on 2025-04-05 23:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FE', '0073_eventocontingencia_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventocontingencia',
            name='factura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detalles_dte', to='FE.facturaelectronica'),
        ),
        migrations.AddField(
            model_name='eventocontingencia',
            name='motivo_contingencia',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='eventocontingencia',
            name='sello_recepcion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='eventocontingencia',
            name='tipo_contingencia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='FE.tipocontingencia'),
        ),
    ]
