# Generated by Django 5.1.3 on 2025-03-18 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FE', '0074_detallefactura_saldo_favor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventoinvalidacion',
            name='base_imponible',
        ),
        migrations.AddField(
            model_name='detallefactura',
            name='base_imponible',
            field=models.BooleanField(default=False),
        ),
    ]
