# Generated by Django 5.1.3 on 2025-03-18 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FE', '0075_remove_eventoinvalidacion_base_imponible_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallefactura',
            name='base_imponible',
        ),
        migrations.AddField(
            model_name='facturaelectronica',
            name='base_imponible',
            field=models.BooleanField(default=False),
        ),
    ]
