# Generated by Django 5.1.3 on 2025-04-07 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FE', '0075_remove_eventocontingencia_motivo_contingencia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipocontingencia',
            name='motivo_contingencia',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
