# Generated by Django 5.1.3 on 2025-03-18 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FE', '0076_remove_detallefactura_base_imponible_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturaelectronica',
            name='formas_Pago',
            field=models.JSONField(),
        ),
    ]
