# Generated by Django 5.1.3 on 2025-03-18 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FE', '0077_alter_facturaelectronica_formas_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturaelectronica',
            name='formas_Pago',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
