# Generated by Django 5.1.3 on 2025-04-08 20:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FE', '0077_eventocontingencia_recibido_mh'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventocontingencia',
            name='f_fin',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='eventocontingencia',
            name='h_fin',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='eventocontingencia',
            name='h_inicio',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='facturaelectronica',
            name='tipotransmision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='FE.tipotransmision'),
        ),
    ]
