# Generated by Django 5.1.3 on 2025-04-09 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FE', '0078_eventocontingencia_f_fin_eventocontingencia_h_fin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipocontingencia',
            name='descripcion',
            field=models.CharField(max_length=100),
        ),
    ]
