# Generated by Django 5.1.3 on 2025-04-09 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FE', '0079_alter_tipocontingencia_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipocontingencia',
            name='descripcion',
            field=models.CharField(max_length=150),
        ),
    ]
