# Generated by Django 5.1.3 on 2025-04-09 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FE', '0080_alter_tipocontingencia_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturaelectronica',
            name='contingencia_recibida_mh',
            field=models.BooleanField(default=False),
        ),
    ]
