# Generated by Django 5.1.3 on 2025-04-09 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FE', '0082_remove_eventocontingencia_factura_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facturaelectronica',
            name='dtecontingencia',
        ),
        migrations.AddField(
            model_name='eventocontingencia',
            name='factura',
            field=models.ManyToManyField(blank=True, null=True, related_name='detalles_dte', to='FE.facturaelectronica'),
        ),
    ]
