# Generated by Django 5.1.3 on 2025-04-09 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FE', '0083_remove_facturaelectronica_dtecontingencia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventocontingencia',
            name='finalizado',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
