# Generated by Django 5.1.3 on 2025-04-09 21:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FE', '0086_alter_eventocontingencia_factura'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoteContingencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recibido_mh', models.BooleanField(default=False)),
                ('estado', models.BooleanField(default=False)),
                ('lote', models.IntegerField(null=True)),
                ('eventocontingencia', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='FE.eventocontingencia', unique=True)),
            ],
        ),
    ]
