# Generated by Django 5.1.3 on 2025-04-10 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FE', '0090_rename_lote_lotecontingencia_cantidad_lote_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lotecontingencia',
            name='factura_lotes',
            field=models.ManyToManyField(blank=True, related_name='dtes_contingencia', to='FE.facturaelectronica'),
        ),
    ]
