# Generated by Django 5.1.3 on 2025-04-11 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FE', '0092_remove_lotecontingencia_factura_lotes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventocontingencia',
            name='factura',
            field=models.ManyToManyField(blank=True, related_name='facturas', to='FE.facturaelectronica'),
        ),
    ]
