# Generated by Django 5.1.3 on 2025-04-11 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FE', '0093_alter_eventocontingencia_factura'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventocontingencia',
            old_name='fecha_transmicion',
            new_name='fecha_transmision',
        ),
        migrations.AlterField(
            model_name='eventocontingencia',
            name='factura',
            field=models.ManyToManyField(blank=True, related_name='eventos', to='FE.facturaelectronica'),
        ),
        migrations.AlterField(
            model_name='lotecontingencia',
            name='eventocontingencia',
            field=models.ManyToManyField(blank=True, related_name='lotes', to='FE.eventocontingencia'),
        ),
    ]
