# Generated by Django 5.1.3 on 2025-04-12 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FE', '0096_remove_eventocontingencia_factura_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lotecontingencia',
            name='estado',
        ),
    ]
