# Generated by Django 5.1.3 on 2025-04-12 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FE', '0098_eventocontingencia_lotecontingencia_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facturaelectronica',
            name='fecha_modificacion',
        ),
        migrations.RemoveField(
            model_name='facturaelectronica',
            name='hora_modificacion',
        ),
    ]
