# Generated by Django 5.1.3 on 2025-04-12 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FE', '0099_remove_facturaelectronica_fecha_modificacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lotecontingencia',
            name='finalizado',
            field=models.BooleanField(default=False),
        ),
    ]
