# Generated by Django 5.1.3 on 2025-04-14 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FE', '0101_remove_eventocontingencia_lotecontingencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventocontingencia',
            name='lotecontingencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lotes_evento', to='FE.lotecontingencia'),
        ),
    ]
