# Generated by Django 5.1.3 on 2025-04-14 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FE', '0103_alter_lotecontingencia_factura'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventocontingencia',
            name='lotecontingencia',
        ),
        migrations.AddField(
            model_name='lotecontingencia',
            name='evento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lotes_evento', to='FE.eventocontingencia'),
        ),
    ]
