# Generated by Django 5.1.3 on 2025-04-16 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FE', '0108_eventocontingencia_hora_sello_recibido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventocontingencia',
            name='hora_sello_recibido',
        ),
        migrations.AddField(
            model_name='eventocontingencia',
            name='fecha_sello_recibido',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
