# Generated by Django 5.1.3 on 2025-04-16 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FE', '0109_remove_eventocontingencia_hora_sello_recibido_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lotecontingencia',
            name='cantidad_lote',
        ),
        migrations.AddField(
            model_name='eventocontingencia',
            name='cantidad_lote',
            field=models.IntegerField(null=True),
        ),
    ]
