# Generated by Django 5.1.3 on 2025-04-22 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FE', '0110_remove_lotecontingencia_cantidad_lote_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lotecontingencia',
            name='evento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='lotes_contingencia', to='FE.eventocontingencia'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lotecontingencia',
            name='factura',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='lotes_de_factura', to='FE.facturaelectronica'),
            preserve_default=False,
        ),
    ]
