# Generated by Django 5.1.3 on 2025-04-24 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FE', '0110_remove_lotecontingencia_cantidad_lote_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventocontingencia',
            name='motivo_contingencia',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
