# Generated by Django 5.1.3 on 2025-04-25 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FE', '0110_remove_lotecontingencia_cantidad_lote_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventocontingencia',
            name='h_inicio',
        ),
        migrations.AddField(
            model_name='emisor_fe',
            name='representante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='FE.representanteemisor'),
        ),
        migrations.AddField(
            model_name='eventocontingencia',
            name='motivo_contingencia',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
