# Generated by Django 5.1.3 on 2025-04-22 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FE', '0110_remove_lotecontingencia_cantidad_lote_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventocontingencia',
            name='h_inicio',
        ),
        migrations.AddField(
            model_name='facturaelectronica',
            name='fecha_modificacion',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='facturaelectronica',
            name='hora_modificacion',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='lotecontingencia',
            name='evento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lotes_contingencia', to='FE.eventocontingencia'),
        ),
        migrations.AlterField(
            model_name='lotecontingencia',
            name='factura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lotes_de_factura', to='FE.facturaelectronica'),
        ),
    ]
