# Generated by Django 5.1.3 on 2025-04-25 03:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FE', '0111_remove_eventocontingencia_h_inicio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emisor_fe',
            name='representante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='FE.representanteemisor'),
        ),
    ]
