# Generated by Django 5.1.3 on 2025-04-23 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FE', '0111_facturaelectronica_fecha_modificacion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emisor_fe',
            name='representante',
        ),
    ]
