# Generated by Django 5.1.3 on 2025-04-25 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FE', '0111_remove_eventocontingencia_h_inicio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventocontingencia',
            name='motivo_contingencia',
        ),
    ]
