# Generated by Django 5.1.3 on 2025-04-24 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FE', '0111_eventocontingencia_motivo_contingencia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventocontingencia',
            name='h_inicio',
        ),
    ]
