# Generated by Django 5.1.3 on 2025-04-22 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FE', '0112_eventocontingencia_h_inicio'),
    ]

    operations = [
        migrations.CreateModel(
            name='representanteEmisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('numero_documento', models.CharField(max_length=20, unique=True)),
                ('tipo_documento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='FE.tiposdocidreceptor')),
            ],
        ),
    ]
