# Generated by Django 5.1.3 on 2025-04-25 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FE', '0112_remove_eventocontingencia_motivo_contingencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventocontingencia',
            name='motivo_contingencia',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
