# Generated by Django 5.1.3 on 2025-04-22 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FE', '0114_emisor_fe_representante'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventocontingencia',
            name='h_inicio',
        ),
    ]
