# Generated by Django 5.1.3 on 2025-04-26 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FE', '0115_facturaelectronica_envio_coreo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturaelectronica',
            name='envio_coreo',
            field=models.BooleanField(default=False),
        ),
    ]
