# Generated by Django 5.1.3 on 2025-04-26 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FE', '0116_alter_facturaelectronica_envio_coreo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facturaelectronica',
            old_name='envio_coreo',
            new_name='envio_correo',
        ),
        migrations.AddField(
            model_name='facturaelectronica',
            name='envio_correo_contingencia',
            field=models.BooleanField(default=False),
        ),
    ]
