# Generated by Django 5.1.3 on 2025-07-31 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FE', '0118_recintofiscal'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegimenExportacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=250)),
            ],
        ),
        migrations.AlterField(
            model_name='recintofiscal',
            name='descripcion',
            field=models.CharField(max_length=100),
        ),
    ]
