# Generated by Django 5.1.3 on 2025-05-19 15:17

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FE', '0118_emisor_fe_tipocontribuyente'),
        ('INVENTARIO', '0010_compra_clasificacion_compra_numero_documento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacturaSujetoExcluidoElectronica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=50)),
                ('numero_control', models.CharField(blank=True, max_length=31, unique=True)),
                ('codigo_generacion', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('motivocontin', models.CharField(blank=True, max_length=350, null=True)),
                ('fecha_emision', models.DateField(auto_now_add=True)),
                ('hora_emision', models.TimeField(auto_now_add=True)),
                ('descuento', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('total_descuento', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('sub_total', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('iva_retenido', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('retencion_renta', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('total_operaciones', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('total_pagar', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('total_letras', models.CharField(max_length=250, null=True)),
                ('formas_Pago', models.JSONField(blank=True, null=True)),
                ('firmado', models.BooleanField(default=False)),
                ('json_original', models.JSONField()),
                ('json_firmado', models.JSONField(blank=True, null=True)),
                ('sello_recepcion', models.CharField(blank=True, max_length=255, null=True)),
                ('recibido_mh', models.BooleanField(default=False)),
                ('estado', models.BooleanField(default=False)),
                ('contingencia', models.BooleanField(default=False)),
                ('contingencia_recibida_mh', models.BooleanField(default=False)),
                ('fecha_modificacion', models.DateField(auto_now_add=True, null=True)),
                ('hora_modificacion', models.TimeField(auto_now_add=True, null=True)),
                ('envio_correo', models.BooleanField(default=False)),
                ('envio_correo_contingencia', models.BooleanField(default=False)),
                ('condicion_operacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='FE.condicionoperacion')),
                ('dteemisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facturas_emisor_sujeto_excluido_FE', to='FE.emisor_fe')),
                ('dtesujetoexcluido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facturas_sujeto_excluido_FE', to='INVENTARIO.proveedor')),
                ('tipo_dte', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='FE.tipo_dte')),
                ('tipocontingencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='FE.tipocontingencia')),
                ('tipomodelo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='FE.modelofacturacion')),
                ('tipomoneda', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='FE.tipomoneda')),
                ('tipotransmision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='FE.tipotransmision')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleFacturaSujetoExcluido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1, help_text='Cantidad del producto')),
                ('descripcion', models.CharField(blank=True, max_length=150, null=True)),
                ('tipo_item', models.CharField(blank=True, max_length=150, null=True)),
                ('precio_unitario', models.DecimalField(decimal_places=6, help_text='Precio unitario del producto', max_digits=10)),
                ('tiene_descuento', models.BooleanField(default=False)),
                ('descuento', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Porcentaje de descuento aplicado a esta línea', max_digits=5)),
                ('codigo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='INVENTARIO.tipoitem')),
                ('unidad_medida', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='INVENTARIO.tipounidadmedida')),
                ('factura', models.ForeignKey(help_text='Factura a la que pertenece este detalle', on_delete=django.db.models.deletion.CASCADE, related_name='detallesSujetoExcluido', to='FE.facturasujetoexcluidoelectronica')),
            ],
        ),
    ]
