# Generated by Django 5.1.3 on 2025-08-01 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FE', '0119_regimenexportacion_alter_recintofiscal_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='receptor_fe',
            name='pais',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='FE.pais'),
        ),
    ]
