# Generated by Django 5.1.3 on 2025-05-19 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FE', '0120_remove_detallefacturasujetoexcluido_descripcion_and_more'),
        ('INVENTARIO', '0013_remove_productosujetoexcluido_proveedor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallefacturasujetoexcluido',
            name='producto',
            field=models.ForeignKey(help_text='Producto de sujeto exclusivo asociado a este detalle', on_delete=django.db.models.deletion.CASCADE, to='INVENTARIO.productoproveedor'),
        ),
    ]
