# Generated by Django 5.1.3 on 2025-08-02 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FE', '0120_receptor_fe_pais'),
    ]

    operations = [
        migrations.AddField(
            model_name='receptor_fe',
            name='tipo_persona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='FE.tipopersona', verbose_name='Tipo de Persona'),
        ),
    ]
