# Generated by Django 5.1.3 on 2025-08-02 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FE', '0121_receptor_fe_tipo_persona'),
        ('INVENTARIO', '0002_proveedor_actividades_economicas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturaelectronica',
            name='recintoFiscal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='FE.recintofiscal'),
        ),
        migrations.AddField(
            model_name='facturaelectronica',
            name='regimenExportacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='FE.regimenexportacion'),
        ),
        migrations.AddField(
            model_name='facturaelectronica',
            name='tipoItemEmisor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='INVENTARIO.tipoitem'),
        ),
    ]
