# Generated by Django 5.1.3 on 2025-08-02 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FE', '0122_facturaelectronica_recintofiscal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturaelectronica',
            name='flete_exportacion',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='facturaelectronica',
            name='incoterms',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='FE.incoterms'),
        ),
        migrations.AddField(
            model_name='facturaelectronica',
            name='seguro_exportacion',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
