# Generated by Django 5.1.3 on 2025-08-04 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FE', '0123_facturaelectronica_flete_exportacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token_data',
            name='token',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='token_data',
            name='token_type',
            field=models.CharField(default='Bearer', max_length=255),
        ),
    ]
