# Generated by Django 5.1.3 on 2025-09-04 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FE', '0124_alter_token_data_token_alter_token_data_token_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emisor_fe',
            name='nit',
            field=models.CharField(max_length=20, verbose_name='NIT del Emisor'),
        ),
    ]
