# Generated by Django 5.1.3 on 2025-09-08 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FE', '0125_alter_emisor_fe_nit'),
    ]

    operations = [
        migrations.AddField(
            model_name='emisor_fe',
            name='imprime_termica',
            field=models.BooleanField(default=False, verbose_name='Imprimir en térmica (80mm)'),
        ),
    ]
