# Generated by Django 5.1.3 on 2025-09-11 22:13

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FE', '0126_emisor_fe_imprime_termica'),
    ]

    operations = [
        migrations.AddField(
            model_name='receptor_fe',
            name='geocode_source',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='receptor_fe',
            name='geocoded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='receptor_fe',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Latitud (WGS84)', max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(Decimal('-90')), django.core.validators.MaxValueValidator(Decimal('90'))]),
        ),
        migrations.AddField(
            model_name='receptor_fe',
            name='lng',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Longitud (WGS84)', max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(Decimal('-180')), django.core.validators.MaxValueValidator(Decimal('180'))]),
        ),
    ]
