# Generated by Django 5.1.3 on 2025-09-19 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FE', '0127_receptor_fe_geocode_source_receptor_fe_geocoded_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='numerocontrol',
            name='codigo_establicimiento',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='numerocontrol',
            name='codigo_punto_venta',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
