# Generated by Django 5.1.3 on 2025-09-19 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FE', '0128_numerocontrol_codigo_establicimiento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='numerocontrol',
            name='codigo_establicimiento',
        ),
        migrations.AddField(
            model_name='numerocontrol',
            name='codigo_establecimiento',
            field=models.CharField(blank=True, default='0000', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='numerocontrol',
            name='codigo_punto_venta',
            field=models.CharField(blank=True, default='0001', max_length=4, null=True),
        ),
    ]
