# Generated by Django 5.1.3 on 2025-05-07 21:09

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('INVENTARIO', '0009_ajusteinventario_movimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='clasificacion',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='compra',
            name='numero_documento',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='compra',
            name='sector',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='compra',
            name='tipo_costo_gasto',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='compra',
            name='tipo_documento',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='compra',
            name='tipo_operacion',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='detallecompra',
            name='iva_item',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='detallecompra',
            name='tipo_compra',
            field=models.CharField(choices=[('EX_INT', 'Interna Exenta'), ('EX_INT_NO', 'Internaciones Exentas/No Sujetas'), ('EX_IMP', 'Importaciones Exentas/No Sujetas'), ('GR_INT', 'Interna Gravada'), ('GR_INT_B', 'Internaciones Grav. Bienes'), ('GR_IMP_B', 'Importaciones Grav. Bienes'), ('GR_IMP_S', 'Importaciones Grav. Servicios')], default='GR_INT', max_length=12),
        ),
        migrations.AlterField(
            model_name='compra',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='detallecompra',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='detallecompra',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14),
        ),
    ]
