# Generated by Django 5.1.3 on 2025-05-20 04:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FE', '0122_remove_facturasujetoexcluidoelectronica_dteemisor'),
        ('INVENTARIO', '0014_delete_productosujetoexcluido'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='tipo_documento',
            field=models.ForeignKey(blank=True, help_text='DUI, NIT, etc.', null=True, on_delete=django.db.models.deletion.CASCADE, to='FE.tiposdocidreceptor'),
        ),
    ]
