"""
Django settings for intracoe project.

Generated by 'django-admin startproject' using Django 5.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure--t^=e+nnmjaah90onb$_&@5(kv1-_c!sjr^y1vov!(v0!5wa$a'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS=['*']

CSRF_TRUSTED_ORIGINS = [
    'https://*.contaspro.cloud',
    'https://*.pluginsv.com',
    'http://localhost:*',
    'http://127.0.0.1:*',
]

CORS_ALLOW_ALL_ORIGINS = True
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

CORS_ALLOW_CREDENTIALS = True

CORS_ALLOW_HEADERS = [
    'content-type',
    'authorization',
    'accept',
    # otros encabezados que necesites
]

CSRF_TRUSTED_ORIGINS = [
    'http://127.0.0.1:8000',
    'http://127.0.0.1',
    'http://localhost:8000',
    'http://localhost',
    'http://0.0.0.0:8000',
    'http://0.0.0.0',
    'https://intracoe.incoe.cloud',
    'http://intracoe.incoe.cloud',
    'https://192.168.100.81',
    'http://localhost:5173',  # Puerto de tu frontend (React)
    'http://127.0.0.1:5173',  # Alternativa para localhost
    'http://localhost:5174',  # Puerto de tu frontend (React)
    'http://127.0.0.1:5174',  # Alternativa para localhost
    
]

## CONFIGURACION DE CORREOS ##############################

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'mail.grupoincoe.com'
EMAIL_PORT = 465
EMAIL_USE_SSL = True  # Cambiado de TLS a SSL
EMAIL_USE_TLS = False  # Deshabilitado el TLS
EMAIL_HOST_USER = 'talentohumano@grupoincoe.com'
EMAIL_HOST_PASSWORD = '*J{jLiwCF)E?'

EMAIL_BACKEND_FE = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST_FE = 'mail.grupoincoe.com'
EMAIL_PORT_FE = 465
EMAIL_USE_SSL_FE = True  # Cambiado de TLS a SSL
EMAIL_USE_TLS_FE = False  # Deshabilitado el TLS
EMAIL_HOST_USER_FE = 'facturacion@grupoincoe.com'
EMAIL_HOST_PASSWORD_FE = 'F4ctur4c10n.23'

EMAIL_BACKEND_QUEDAN = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST_QUEDAN = 'mail.grupoincoe.com'
EMAIL_PORT_QUEDAN = 465
EMAIL_USE_SSL_QUEDAN = True  # Cambiado de TLS a SSL
EMAIL_USE_TLS_QUEDAN = False  # Deshabilitado el TLS
EMAIL_HOST_USER_QUEDAN = 'facturacion@grupoincoe.com'
EMAIL_HOST_PASSWORD_QUEDAN = 'F4ctur4c10n.23'

############################################################

#### JUSTES DE LOGIN ###############################

LOGOUT_REDIRECT_URL = '/login/'  # URL a la que se redirige después del logout
LOGIN_REDIRECT_URL = '/'          # Página a la que se redirige después del login
LOGIN_URL = '/login/'
LOGIN_ERROR_URL = '/login/'
LOGIN_ERROR_MESSAGE = 'Credenciales incorrectas'

########################################################

## REST FRAMEWORK LOGIN CONFIGURATION

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        #'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.TokenAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    # 'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    # 'PAGE_SIZE': 10,
}

# Caducidad de la cookie de sesión: 8 horas
SESSION_COOKIE_AGE = 28800

# Renueva la cookie en cada petición (reinicia el contador con cada request)
SESSION_SAVE_EVERY_REQUEST = True

# La sesión NO expira al cerrar el navegador
SESSION_EXPIRE_AT_BROWSER_CLOSE = False

# Application definition

INSTALLED_APPS = [
    "daphne",
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',
    'widget_tweaks',
    'django_select2',
    'RRHH',
    'FE',
    'CONTABILIDAD',
    'INFORMATICA',
    'INVENTARIO.apps.InventarioConfig',
    'corsheaders',
    'AUTENTICACION',
    "channels",
    'RESTAURANTE',
]
AUTH_USER_MODEL = "AUTENTICACION.User"

MIDDLEWARE = [
    "middleware.setup_check.SetupRedirectMiddleware",
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'middleware.demo_protection.DemoProtectionMiddleware',
]

ROOT_URLCONF = 'intracoe.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'templates'),
            os.path.join(BASE_DIR, 'templates/includes'),
            os.path.join(BASE_DIR, 'FE/templates'),
            os.path.join(BASE_DIR, 'RRHH/templates'),
            os.path.join(BASE_DIR, 'CONTABILIDAD/templates'),
            os.path.join(BASE_DIR, 'INFORMATICA/templates'),
            os.path.join(BASE_DIR, 'INVENTARIO/templates'),
            os.path.join(BASE_DIR, 'AUTENTICACION/templates'),
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                "FE.context_processors.emisor_context",
            ],
        },
    },
]

WSGI_APPLICATION = 'intracoe.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

# ── Base de datos: lee de db_config.json si existe, sino usa SQLite ──
import json as _json
from pathlib import Path as _Path

# Buscar en /app/config/ (Docker volumen) o en la raíz del proyecto
_db_config_path = _Path('/app/config/db_config.json')
if not _db_config_path.exists():
    _db_config_path = BASE_DIR / 'db_config.json'

_db_conf = None
if _db_config_path.exists():
    try:
        with open(_db_config_path) as _f:
            _db_conf = _json.load(_f)
    except (ValueError, _json.JSONDecodeError):
        _db_conf = None

if _db_conf and isinstance(_db_conf, dict) and _db_conf.get('host'):
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': _db_conf.get('name', 'intracoe'),
            'USER': _db_conf.get('user', 'postgres'),
            'PASSWORD': _db_conf.get('password', ''),
            'HOST': _db_conf.get('host', 'localhost'),
            'PORT': _db_conf.get('port', '5432'),
        },
    }
else:
    # SQLite de bootstrap — permite arrancar el wizard sin PostgreSQL
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db_bootstrap.sqlite3',
        },
    }

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend', 
    'intracoe.backends_login.MultiRoleBackend',
]


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators
# settings.py

# ... debajo de AUTH_PASSWORD_VALIDATORS ...


AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]



# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

# Configuración regional para El Salvador
LANGUAGE_CODE = 'es-SV'
TIME_ZONE = 'America/El_Salvador'
USE_I18N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_DIRS = [BASE_DIR / "static"]
STATICFILES_STORAGE = 'whitenoise.storage.CompressedStaticFilesStorage'


# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

#URL LOCAL PARA GUARDAR ARCHIVOS

URL_ARCHIVOS_CORREO = "/factura_pdf"



ASGI_APPLICATION = "intracoe.asgi.application"

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '[{levelname}] {asctime} {module} {message}',
            'style': '{',
        },
        'simple': {
            'format': '[{levelname}] {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
        'file': {
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'logs' / 'django.log',
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'WARNING',
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'FE': {
            'handlers': ['console', 'file'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'RESTAURANTE': {
            'handlers': ['console', 'file'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'CONTABILIDAD': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
        'INFORMATICA': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
        'AUTENTICACION': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
        'intracoe': {
            'handlers': ['console', 'file'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'INVENTARIO': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}

CHANNEL_LAYERS = {
    "default": {"BACKEND": "channels.layers.InMemoryChannelLayer"}
}