from rest_framework import serializers

class AnexoConsumidorFinalRowSerializer(serializers.Serializer):
    fecha = serializers.CharField()
    clase = serializers.CharField()
    tipo = serializers.CharField()
    numero_resolucion = serializers.CharField(allow_blank=True)
    serie_documento = serializers.CharField(allow_blank=True)
    control_interno_del = serializers.CharField(allow_blank=True)
    control_interno_al = serializers.CharField(allow_blank=True)
    numero_doc_del = serializers.CharField(allow_blank=True)
    numero_doc_al = serializers.CharField(allow_blank=True)
    numero_maquina = serializers.CharField(allow_blank=True)
    ventas_exentas = serializers.DecimalField(max_digits=12, decimal_places=2)
    ventas_internas_exentas = serializers.DecimalField(max_digits=12, decimal_places=2)
    ventas_no_sujetas = serializers.DecimalField(max_digits=12, decimal_places=2)
    ventas_gravadas = serializers.DecimalField(max_digits=12, decimal_places=2)
    exportaciones_dentro = serializers.DecimalField(max_digits=12, decimal_places=2)
    exportaciones_fuera = serializers.DecimalField(max_digits=12, decimal_places=2)
    exportaciones_servicio = serializers.DecimalField(max_digits=12, decimal_places=2)
    ventas_zonas_francas = serializers.DecimalField(max_digits=12, decimal_places=2)
    ventas_cuenta_terceros = serializers.DecimalField(max_digits=12, decimal_places=2)
    total_ventas = serializers.DecimalField(max_digits=12, decimal_places=2)
    tipo_operacion = serializers.CharField(allow_blank=True)
    tipo_ingreso = serializers.CharField(allow_blank=True)
    numero_anexo = serializers.CharField()